#pragma once
// HoverController.h — a sample @PROJECT_NAME@ script (generated by Starforge).
//
// A script is a C++ class deriving from Cosmic::ScriptableEntity. Public fields
// show up in the Inspector and serialize with the scene; override the lifecycle
// callbacks you need. This one eases its entity toward TargetAltitude each frame.

#include <Cosmic.h>

class HoverController : public Cosmic::ScriptableEntity
{
public:
    float TargetAltitude = 5.0f;   // metres — where the entity settles
    float Kp = 2.0f;               // proportional gain
    float Kd = 0.4f;               // damping gain (on vertical velocity)

protected:
    void OnUpdate(float ts) override;

private:
    float m_VelY = 0.0f;
};
