#pragma once
// PaddleController.h — a sample @PROJECT_NAME@ script (generated by Starforge).
//
// The ForgePong paddle (Phase 17 / U8): six lines of gameplay. Moves the
// entity's sprite up/down with W/S (or the arrow keys when UseArrows is set,
// for the right-hand player) and clamps it to the court.

#include <Cosmic.h>

class PaddleController : public Cosmic::ScriptableEntity
{
public:
    float Speed     = 9.0f;    // world units per second
    float LimitY    = 3.4f;    // court half-height minus half a paddle
    bool  UseArrows = false;   // false = W/S, true = Up/Down

protected:
    void OnUpdate(float ts) override
    {
        using namespace Cosmic;
        auto& p = GetComponent<TransformComponent>().Position;
        const bool up   = Input::IsKeyPressed(UseArrows ? CS_KEY_UP   : CS_KEY_W);
        const bool down = Input::IsKeyPressed(UseArrows ? CS_KEY_DOWN : CS_KEY_S);
        p.y += ((up ? 1.0f : 0.0f) - (down ? 1.0f : 0.0f)) * Speed * ts;
        p.y  = glm::clamp(p.y, -LimitY, LimitY);
    }
};
