#pragma once
// PhysicsBall.h — a sample @PROJECT_NAME@ script (generated by Starforge).
//
// A telemetry reporter for a *physics-driven* ball. Unlike BouncingBall (which
// integrates its own bounce), this entity is a real dynamic rigid body — attach a
// RigidBodyComponent (Dynamic) + a SphereColliderComponent and let the engine
// physics do the falling/bouncing. This script only READS the result each fixed
// step and pushes it as telemetry, so you can plot the ball's height + vertical
// speed live in the Telemetry panel during Play (View > Telemetry).

#include <Cosmic.h>

class PhysicsBall : public Cosmic::ScriptableEntity
{
protected:
    void OnFixedUpdate(float /*dt*/) override
    {
        const float y = GetComponent<Cosmic::TransformComponent>().Position.y;
        Telemetry().Push("height", y);                 // world height from the transform
        Telemetry().Push("velY", Physics().GetVelocity().y);   // vertical speed from the body
    }
};
