#pragma once
// WalkController.h — a sample @PROJECT_NAME@ script (generated by Starforge).
//
// A first-person-style ground walker built on the engine character controller
// (Jolt CharacterVirtual). Attach it to an entity that also has a
// CharacterControllerComponent; then WASD / the left stick walk and Space / a
// gamepad button jump. Movement is world-relative (no camera coupling) to keep
// this a minimal copy-paste starting point — swap in your camera basis to make it
// view-relative.

#include <Cosmic.h>

#include <cmath>

class WalkController : public Cosmic::ScriptableEntity
{
public:
    float MoveSpeed = 4.0f;    // metres / second
    float JumpSpeed = 5.0f;    // launch velocity (apex height ~= JumpSpeed^2 / 19.6)

protected:
    void OnFixedUpdate(float /*dt*/) override
    {
        using namespace Cosmic;

        glm::vec3 dir(0.0f);
        if (Input::IsKeyPressed(CS_KEY_W)) dir.z -= 1.0f;   // forward = -Z
        if (Input::IsKeyPressed(CS_KEY_S)) dir.z += 1.0f;
        if (Input::IsKeyPressed(CS_KEY_A)) dir.x -= 1.0f;
        if (Input::IsKeyPressed(CS_KEY_D)) dir.x += 1.0f;

        // Gamepad left stick with a deadzone.
        const float gx = Input::GetGamepadAxis(CS_GAMEPAD_AXIS_LEFT_X);
        const float gy = Input::GetGamepadAxis(CS_GAMEPAD_AXIS_LEFT_Y);
        if (std::fabs(gx) > 0.2f) dir.x += gx;
        if (std::fabs(gy) > 0.2f) dir.z += gy;

        if (glm::length(dir) > 1.0f)
            dir = glm::normalize(dir);

        // Drive the character each fixed step (the Scene ticks it after physics).
        Character().Move(dir * MoveSpeed);

        if (Input::IsKeyPressed(CS_KEY_SPACE) && Character().IsGrounded())
            Character().Jump(JumpSpeed);
    }
};
