#pragma once
// BouncingBall.h — a sample @PROJECT_NAME@ script (generated by Starforge).
//
// A ball under gravity that bounces off the ground (y = 0), losing a little
// energy each bounce. It PUSHES two telemetry channels every fixed step —
// Telemetry().Push(name, value) — so you can plot them live in the Telemetry
// panel during Play (View ▸ Telemetry) without marking any Inspector field.

#include <Cosmic.h>

class BouncingBall : public Cosmic::ScriptableEntity
{
public:
    float Gravity     = -9.81f;   // m/s^2
    float Restitution = 0.8f;     // fraction of speed kept per bounce
    float StartHeight = 5.0f;     // metres ABOVE the floor to drop from
    float FloorY      = 0.0f;     // world Y of the ground it bounces on

protected:
    void OnStart() override
    {
        GetComponent<Cosmic::TransformComponent>().Position.y = FloorY + StartHeight;
        m_VelY = 0.0f;
    }

    void OnFixedUpdate(float dt) override;

private:
    float m_VelY = 0.0f;
};
