#pragma once
// PidController.h — a sample @PROJECT_NAME@ script (generated by Starforge).
//
// A PID loop that drives its entity's altitude to Target and pushes the tracking
// `error` (plus the controller `output`) as telemetry each fixed step. Pair it
// with BouncingBall in one scene to record both while you Play, then Stop and
// scrub / export the take (View ▸ Telemetry).

#include <Cosmic.h>

class PidController : public Cosmic::ScriptableEntity
{
public:
    float Target = 3.0f;   // desired altitude (m)
    float Kp = 6.0f;
    float Ki = 0.5f;
    float Kd = 1.2f;

protected:
    void OnFixedUpdate(float dt) override;

private:
    float m_VelY     = 0.0f;
    float m_Integral = 0.0f;
};
