#pragma once
// PongBall.h — a sample @PROJECT_NAME@ script (generated by Starforge).
//
// The ForgePong ball (Phase 17 / U8): kinematic 2D bounce — reflects off the
// court's top/bottom, deflects off the two paddles ("PaddleL"/"PaddleR" AABB,
// steering by hit offset and speeding up per return), scores on the side
// walls, writes the "ScoreL"/"ScoreR" UiText labels, restarts the "HitFx"
// flipbook at each impact, and emits left_wins / right_wins on match point —
// the signals the ForgePong flow routes to its Win screen.

#include <Cosmic.h>
#include "scene/ui/UiComponents.h"   // UiTextComponent (the score labels)

#include <string>

class PongBall : public Cosmic::ScriptableEntity
{
public:
    float Speed      = 7.0f;    // serve speed (units/s); grows by SpeedUp per return
    float SpeedUp    = 1.06f;
    float CourtHalfW = 8.0f;    // scoring walls
    float CourtHalfH = 4.2f;    // bounce walls
    int   WinScore   = 5;

protected:
    void OnStart() override
    {
        Serve(-1.0f);
        WriteScores();
    }

    void OnUpdate(float ts) override
    {
        using namespace Cosmic;
        auto& t = GetComponent<TransformComponent>();
        t.Position.x += m_Vel.x * ts;
        t.Position.y += m_Vel.y * ts;

        // Top/bottom bounce.
        if (t.Position.y >  CourtHalfH && m_Vel.y > 0.0f) { m_Vel.y = -m_Vel.y; Hit(t.Position); }
        if (t.Position.y < -CourtHalfH && m_Vel.y < 0.0f) { m_Vel.y = -m_Vel.y; Hit(t.Position); }

        // Paddle deflection: AABB (padded by the ball radius) + inbound check.
        auto& reg = GetScene().GetRegistry();
        for (auto e : reg.view<TagComponent, TransformComponent, SpriteRendererComponent>())
        {
            const std::string& tag = reg.get<TagComponent>(e).Tag;
            if (tag != "PaddleL" && tag != "PaddleR")
                continue;
            const auto& pt = reg.get<TransformComponent>(e);
            const float hw = pt.Scale.x * 0.5f + 0.15f;
            const float hh = pt.Scale.y * 0.5f + 0.15f;
            const float dx = t.Position.x - pt.Position.x;
            const float dy = t.Position.y - pt.Position.y;
            if (std::abs(dx) > hw || std::abs(dy) > hh)
                continue;
            const bool inbound = (tag == "PaddleL") ? (m_Vel.x < 0.0f) : (m_Vel.x > 0.0f);
            if (!inbound)
                continue;
            m_Vel.x  = -m_Vel.x * SpeedUp;
            m_Vel.y += (dy / hh) * 3.0f;   // steer by where the paddle was struck
            Hit(t.Position);
        }

        // Scoring (ball fully past a side wall).
        if (t.Position.x >  CourtHalfW + 0.5f) Point(/*leftScored*/ true);
        if (t.Position.x < -CourtHalfW - 0.5f) Point(/*leftScored*/ false);

        // Park the one-shot hit effect once its clip has played out.
        if (m_FxCooldown > 0.0f && (m_FxCooldown -= ts) <= 0.0f)
            MoveFx({ 0.0f, 1000.0f, 0.0f }, false);
    }

private:
    void Serve(float dir)
    {
        auto& t = GetComponent<Cosmic::TransformComponent>();
        t.Position.x = 0.0f;
        t.Position.y = 0.0f;
        m_Vel = { Speed * dir, ((m_ScoreL + m_ScoreR) % 2 == 0) ? 2.0f : -2.0f };
    }

    void Point(bool leftScored)
    {
        (leftScored ? m_ScoreL : m_ScoreR)++;
        WriteScores();
        if (m_ScoreL >= WinScore) Signals().Emit("left_wins");
        if (m_ScoreR >= WinScore) Signals().Emit("right_wins");
        Serve(leftScored ? -1.0f : 1.0f);   // loser serves toward the winner
    }

    void WriteScores()
    {
        using namespace Cosmic;
        auto& reg = GetScene().GetRegistry();
        for (auto e : reg.view<TagComponent, UiTextComponent>())
        {
            const std::string& tag = reg.get<TagComponent>(e).Tag;
            if (tag == "ScoreL") reg.get<UiTextComponent>(e).Text = std::to_string(m_ScoreL);
            if (tag == "ScoreR") reg.get<UiTextComponent>(e).Text = std::to_string(m_ScoreR);
        }
    }

    void Hit(const glm::vec3& at)
    {
        MoveFx({ at.x, at.y, at.z + 0.1f }, true);
    }

    // Position the "HitFx" flipbook sprite and (re)start / stop its clip.
    void MoveFx(const glm::vec3& pos, bool play)
    {
        using namespace Cosmic;
        auto& reg = GetScene().GetRegistry();
        for (auto e : reg.view<TagComponent, SpriteAnimationComponent, TransformComponent>())
        {
            if (reg.get<TagComponent>(e).Tag != "HitFx")
                continue;
            reg.get<TransformComponent>(e).Position = pos;
            auto& anim = reg.get<SpriteAnimationComponent>(e);
            anim.Elapsed = 0.0f;
            anim.Playing = play;
            if (play && anim.FPS > 0.0f)
                m_FxCooldown = (float)anim.Frames / anim.FPS;
            break;
        }
    }

    glm::vec2 m_Vel{ 0.0f, 0.0f };
    int   m_ScoreL = 0, m_ScoreR = 0;
    float m_FxCooldown = 0.0f;
};
