#pragma once
// StoryUiBinding.h — a sample @PROJECT_NAME@ script (generated by Starforge).
//
// The STOCK zero-code binding for the Starforge Story Graph (Phase 25 / Q3):
// attach it to any entity in a scene that also holds a UI canvas, point StoryPath
// at a `.cstory`, and author the UI entities it drives (by Tag). Each frame it
// maps the runner's CURRENT node onto those UI entities and its VALID options
// onto a fixed set of option buttons — a branching, guarded dialogue plays with
// no gameplay code. Copy + adapt freely; the engine ships only the RUNNER
// (scene/StoryGraph.h), never presentation.
//
// Author these entities under your canvas (Tags below are the defaults):
//   * a UiText  tagged "StoryText"       — the line of dialogue
//   * a UiText  tagged "StorySpeaker"    — the speaker name (optional)
//   * a UiImage tagged "StoryPortrait"   — the speaker portrait (optional)
//   * a UiImage tagged "StoryBackground" — the scene background (optional)
//   * up to MaxOptions button entities tagged "StoryOption0".."StoryOption3",
//     each a UiButton (+ a UiText for its label). The binding fills their label,
//     shows/hides them by validity, and rewrites their Signal to "story_choose_i".
//
// Variables ride Q2: if this scene runs under a `.cflow`, the story shares the
// flow blackboard, so guarded options can read flow variables.

#include <Cosmic.h>
#include "scene/StoryGraph.h"

#include <cstdlib>
#include <string>

class StoryUiBinding : public Cosmic::ScriptableEntity
{
public:
    std::string StoryPath       = "project://stories/Intro.cstory";
    std::string TextTag         = "StoryText";
    std::string SpeakerTag      = "StorySpeaker";
    std::string PortraitTag     = "StoryPortrait";
    std::string BackgroundTag   = "StoryBackground";
    std::string OptionTagPrefix = "StoryOption";   // + index (0..MaxOptions-1)

    static constexpr int MaxOptions = 4;           // pre-authored option-button slots

protected:
    void OnStart() override
    {
        Cosmic::StoryGraph graph;
        if (Cosmic::StoryGraph::Load(graph, StoryPath))
            m_Runner.Start(graph, &GetScene(), GetScene().ActiveFlow());   // share flow vars if any
        Refresh();
    }

    void OnSignal(const std::string& signal, Cosmic::Entity /*source*/) override
    {
        // Option buttons emit "story_choose_<validIndex>" (rewritten in Refresh).
        static const std::string kPrefix = "story_choose_";
        if (signal.rfind(kPrefix, 0) == 0)
        {
            m_Runner.Choose(std::atoi(signal.c_str() + kPrefix.size()));
            Refresh();
        }
    }

private:
    Cosmic::Entity FindByTag(const std::string& tag)
    {
        auto& reg = GetScene().GetRegistry();
        for (auto e : reg.view<Cosmic::TagComponent>())
            if (reg.get<Cosmic::TagComponent>(e).Tag == tag)
                return Cosmic::Entity(e, &GetScene());
        return {};
    }

    static void SetText(Cosmic::Entity e, const std::string& text)
    {
        if (e && e.HasComponent<Cosmic::UiTextComponent>())
            e.GetComponent<Cosmic::UiTextComponent>().Text = text;
    }
    static void SetImage(Cosmic::Entity e, const std::string& path)
    {
        if (e && e.HasComponent<Cosmic::UiImageComponent>())
            e.GetComponent<Cosmic::UiImageComponent>().TexturePath = path;
    }

    void Refresh()
    {
        using namespace Cosmic;
        const StoryNode* node = m_Runner.Current();

        SetText (FindByTag(TextTag),       node ? node->Text : std::string());
        SetText (FindByTag(SpeakerTag),    node ? node->Speaker : std::string());
        SetImage(FindByTag(PortraitTag),   node ? node->PortraitPath : std::string());
        SetImage(FindByTag(BackgroundTag), node ? node->BackgroundPath : std::string());

        const std::vector<int>& valid = m_Runner.ValidOptions();
        for (int i = 0; i < MaxOptions; ++i)
        {
            Entity btn = FindByTag(OptionTagPrefix + std::to_string(i));
            if (!btn) continue;

            const bool show = node && i < (int)valid.size();
            if (btn.HasComponent<TagComponent>())
                btn.GetComponent<TagComponent>().Active = show;   // hide the whole subtree when unused
            if (!show) continue;

            if (btn.HasComponent<UiButtonComponent>())
                btn.GetComponent<UiButtonComponent>().Signal = "story_choose_" + std::to_string(i);
            SetText(btn, node->Options[(size_t)valid[i]].Text);
        }
    }

    Cosmic::StoryRunner m_Runner;
};
