#pragma once
// VoxelDigger.h — a sample @PROJECT_NAME@ script (generated by Starforge).
//
// Demonstrates the Phase 18 voxel script API (Voxels()): LMB breaks the solid
// block in front of this entity, RMB places the active block on the face it hits.
// The ray starts at the entity's world position (raised to eye height) and points
// along its forward (-Z). Pair it with a WalkController + CharacterControllerComponent
// on a player, or put it on the primary camera, to walk-and-dig a voxel world.

#include <Cosmic.h>

class VoxelDigger : public Cosmic::ScriptableEntity
{
public:
    float Reach      = 6.0f;    // max edit distance (world metres)
    int   PlaceBlock = 1;       // palette id RMB places (1 = grass in the default palette)
    float EyeHeight  = 1.6f;    // ray origin lift above the entity origin

protected:
    void OnUpdate(float /*ts*/) override
    {
        using namespace Cosmic;

        const glm::mat4 world = GetScene().GetWorldTransform(GetEntity());
        glm::vec3 origin = glm::vec3(world[3]);
        origin.y += EyeHeight;
        const glm::vec3 fwd = glm::normalize(glm::vec3(world * glm::vec4(0.0f, 0.0f, -1.0f, 0.0f)));

        const bool lmb = Input::IsMouseButtonPressed(CS_MOUSE_BUTTON_LEFT);
        const bool rmb = Input::IsMouseButtonPressed(CS_MOUSE_BUTTON_RIGHT);
        if (lmb && !m_LmbWas) Voxels().Break(origin, fwd, Reach);
        if (rmb && !m_RmbWas) Voxels().Place(origin, fwd, Reach, (uint16_t)PlaceBlock);
        m_LmbWas = lmb;
        m_RmbWas = rmb;
    }

private:
    bool m_LmbWas = false;
    bool m_RmbWas = false;
};
