#pragma once

// FirmwareTemplates.h — SF_Telem
// ============================================================================
// Embedded Arduino sketch sources so the app can hand you a ready-to-flash .ino
// with your chosen telemetry pins baked in (Serial Link -> Arduino Firmware ->
// Copy). Pin numbers are token placeholders ({{RIGHT_PIN}} etc.) substituted at
// copy time. These MIRROR firmware/*.ino (default pins 16/17/13) — keep them in
// sync if the firmware changes.
// ============================================================================

#include <string>

namespace Workspace
{
    inline std::string ReplaceAll(std::string s, const std::string& from, const std::string& to)
    {
        if (from.empty()) return s;
        size_t pos = 0;
        while ((pos = s.find(from, pos)) != std::string::npos)
        {
            s.replace(pos, from.size(), to);
            pos += to.size();
        }
        return s;
    }

    // --- Main firmware: 2 drive + 1 weapon ESC (mirrors sf_telem_esp32.ino) ---
    inline std::string BuildMainFirmware(int rightPin, int leftPin, int weaponPin)
    {
        static const char* templ = R"FW(// ============================================================================
// sf_telem_esp32.ino  —  SF_Telem firmware (2 DRIVE ESCs + 1 WEAPON ESC)
// ============================================================================
//  Generated by the SF_Telem app (Serial Link -> Arduino Firmware -> Copy).
//  ESP32-WROOM-32 / 30-pin dev module. Frame: $<S>,<temp>,<vraw>,<iraw>,<craw>,
//  <erpmraw>*<HH>  (S = 'R','L','W'). Change the *_TLM_PIN defines to move a wire.
//
//  RIGHT drive -> UART1 RX,  LEFT drive -> UART2 RX,  WEAPON -> UART0 RX (remapped;
//  TX kept on GPIO1 for USB). Common ground required.
// ============================================================================

#include <Arduino.h>
#include "BluetoothSerial.h"

#define BT_DEVICE_NAME  "SF_Telem"
#define RIGHT_TLM_PIN   {{RIGHT_PIN}}      // RIGHT drive ESC telemetry -> UART1 RX
#define LEFT_TLM_PIN    {{LEFT_PIN}}      // LEFT  drive ESC telemetry -> UART2 RX
#define WEAPON_TLM_PIN  {{WEAPON_PIN}}      // WEAPON ESC telemetry -> UART0 (Serial) RX (remapped)
#define ESC_BAUD        115200
#define SIDE_STALE_MS   600     // no valid packet within this -> "ERR" in heartbeat

HardwareSerial  SerialRight(1); // UART1
HardwareSerial  SerialLeft(2);  // UART2
BluetoothSerial SerialBT;

enum { R = 0, L = 1, W = 2, N = 3 };
const char SIDE_CHAR[N] = { 'R', 'L', 'W' };

struct ESC_Data
{
    uint8_t  temp        = 0;
    uint16_t voltage     = 0;
    uint16_t current     = 0;
    uint16_t consumption = 0;
    uint16_t erpm        = 0;
    bool     valid       = false;
};

ESC_Data      tlm[N];
uint8_t       buf[N][10];
unsigned long lastMs[N]      = { 0, 0, 0 };
unsigned long lastHeartbeat  = 0;

// ---- KISS CRC8 -------------------------------------------------------------
uint8_t update_crc8(uint8_t crc, uint8_t crc_seed)
{
    uint8_t crc_u = crc ^ crc_seed;
    for (int i = 0; i < 8; i++)
        crc_u = (crc_u & 0x80) ? (0x07 ^ (crc_u << 1)) : (crc_u << 1);
    return crc_u;
}

uint8_t get_crc8(uint8_t* b, uint8_t size)
{
    uint8_t crc = 0;
    for (uint8_t i = 0; i < size; i++) crc = update_crc8(b[i], crc);
    return crc;
}

bool parseESC(uint8_t* buffer, ESC_Data& d)
{
    if (get_crc8(buffer, 9) != buffer[9]) return false;
    d.temp        = buffer[0];
    d.voltage     = (buffer[1] << 8) | buffer[2];
    d.current     = (buffer[3] << 8) | buffer[4];
    d.consumption = (buffer[5] << 8) | buffer[6];
    d.erpm        = (buffer[7] << 8) | buffer[8];
    d.valid       = true;
    return true;
}

// ---- Output helpers --------------------------------------------------------
void broadcastPrint(const char* msg)
{
    Serial.print(msg);
    if (SerialBT.connected()) SerialBT.print(msg);
}

void sendFrame(char side, const ESC_Data& d)
{
    char payload[48];
    int n = snprintf(payload, sizeof(payload), "%c,%u,%u,%u,%u,%u",
                     side, (unsigned)d.temp, (unsigned)d.voltage, (unsigned)d.current,
                     (unsigned)d.consumption, (unsigned)d.erpm);
    if (n <= 0) return;
    uint8_t crc = 0;
    for (int i = 0; i < n; i++) crc ^= (uint8_t)payload[i];
    char frame[64];
    snprintf(frame, sizeof(frame), "$%s*%02X\n", payload, crc);
    broadcastPrint(frame);
}

bool serviceSide(Stream& port, int idx)
{
    if (port.available() > 50) while (port.available()) port.read();  // resync guard
    bool sent = false;
    if (port.available() >= 10)
    {
        port.readBytes(buf[idx], 10);
        if (parseESC(buf[idx], tlm[idx]))
        {
            sendFrame(SIDE_CHAR[idx], tlm[idx]);
            tlm[idx].valid = false;
            sent = true;
        }
    }
    return sent;
}

void setup()
{
    // UART0 / Serial: RX remapped to the WEAPON pin, TX kept on GPIO1 for USB.
    Serial.begin(115200, SERIAL_8N1, WEAPON_TLM_PIN, 1);
    delay(1000);
    SerialRight.begin(ESC_BAUD, SERIAL_8N1, RIGHT_TLM_PIN, -1, false);
    SerialLeft.begin(ESC_BAUD, SERIAL_8N1, LEFT_TLM_PIN,  -1, false);
    SerialBT.begin(BT_DEVICE_NAME);
    Serial.println("# Telemetry System Online (2 drive + 1 weapon ESC)");
    Serial.printf("# RIGHT pin: %d (UART1)   LEFT pin: %d (UART2)   WEAPON pin: %d (UART0)\n",
                  RIGHT_TLM_PIN, LEFT_TLM_PIN, WEAPON_TLM_PIN);
}

void loop()
{
    if (serviceSide(SerialRight, R)) lastMs[R] = millis();
    if (serviceSide(SerialLeft,  L)) lastMs[L] = millis();
    if (serviceSide(Serial,      W)) lastMs[W] = millis();

    if (millis() - lastHeartbeat > 1000)
    {
        const bool rOk = (millis() - lastMs[R]) < SIDE_STALE_MS;
        const bool lOk = (millis() - lastMs[L]) < SIDE_STALE_MS;
        const bool wOk = (millis() - lastMs[W]) < SIDE_STALE_MS;
        char status[80];
        snprintf(status, sizeof(status), "# R=%s L=%s W=%s bt=%s\n",
                 rOk ? "ok" : "ERR", lOk ? "ok" : "ERR", wOk ? "ok" : "ERR",
                 SerialBT.connected() ? "yes" : "no");
        broadcastPrint(status);
        lastHeartbeat = millis();
    }
}
)FW";

        std::string s = templ;
        s = ReplaceAll(s, "{{RIGHT_PIN}}",  std::to_string(rightPin));
        s = ReplaceAll(s, "{{LEFT_PIN}}",   std::to_string(leftPin));
        s = ReplaceAll(s, "{{WEAPON_PIN}}", std::to_string(weaponPin));
        return s;
    }

    // --- Simulator: synthesises all 3 ESCs, no real ESC / no pins needed ---
    inline std::string BuildSimulatorFirmware()
    {
        return R"FW(// ============================================================================
// sf_telem_sim_test.ino  —  SF_Telem SIMULATOR (no ESC / no pins needed)
// ============================================================================
//  Generated by the SF_Telem app. Synthesises 2 drive + 1 weapon ESC in the
//  exact wire format and streams it over Bluetooth + USB, to prove the link and
//  pipeline before any real ESC. Set SEND_* to 0 to omit a side.
// ============================================================================

#include <Arduino.h>
#include "BluetoothSerial.h"
#include <math.h>

#define BT_DEVICE_NAME   "SF_Telem"
#define SEND_INTERVAL_MS 25      // ~40 Hz per side
#define SEND_RIGHT   1
#define SEND_LEFT    1
#define SEND_WEAPON  1

BluetoothSerial SerialBT;

struct SimEsc
{
    uint8_t  temp        = 30;
    uint16_t voltage     = 2500; // centi-volts
    uint16_t current     = 0;    // centi-amps
    uint16_t consumption = 0;    // mAh
    uint16_t erpm        = 0;    // eRPM / 100
};

SimEsc simR, simL, simW;
float  mAhR = 0, mAhL = 0, mAhW = 0;
unsigned long lastSend = 0;

void broadcastPrint(const char* msg)
{
    Serial.print(msg);
    if (SerialBT.connected()) SerialBT.print(msg);
}

void sendFrame(char side, const SimEsc& d)
{
    char payload[48];
    int n = snprintf(payload, sizeof(payload), "%c,%u,%u,%u,%u,%u",
                     side, (unsigned)d.temp, (unsigned)d.voltage, (unsigned)d.current,
                     (unsigned)d.consumption, (unsigned)d.erpm);
    if (n <= 0) return;
    uint8_t crc = 0;
    for (int i = 0; i < n; i++) crc ^= (uint8_t)payload[i];
    char frame[64];
    snprintf(frame, sizeof(frame), "$%s*%02X\n", payload, crc);
    broadcastPrint(frame);
}

void fillDrive(SimEsc& d, float throttle, float& mAhAccum, float dt)
{
    throttle = constrain(throttle, 0.0f, 1.0f);
    d.erpm    = (uint16_t)constrain((int)(throttle * 2000.0f) + random(-30, 30), 0, 2400);
    d.current = (uint16_t)constrain((int)(throttle * 4500.0f) + random(-60, 60), 0, 6000);
    d.voltage = (uint16_t)constrain(2500 - (int)(throttle * 220.0f) + random(-8, 8), 2000, 2600);
    d.temp    = (uint8_t)constrain(32 + (int)(throttle * 18.0f) + random(-1, 1), 0, 120);
    mAhAccum += (d.current / 100.0f) * (dt / 3600.0f) * 1000.0f;
    if (mAhAccum > 60000.0f) mAhAccum = 0.0f;
    d.consumption = (uint16_t)mAhAccum;
}

void fillWeapon(SimEsc& d, float throttle, float& mAhAccum, float dt)
{
    throttle = constrain(throttle, 0.0f, 1.0f);
    d.erpm    = (uint16_t)constrain((int)(throttle * 6000.0f) + random(-40, 40), 0, 9000);
    d.current = (uint16_t)constrain((int)(throttle * 7000.0f) + random(-80, 80), 0, 12000);
    d.voltage = (uint16_t)constrain(2500 - (int)(throttle * 300.0f) + random(-8, 8), 1800, 2600);
    d.temp    = (uint8_t)constrain(32 + (int)(throttle * 28.0f) + random(-1, 1), 0, 120);
    mAhAccum += (d.current / 100.0f) * (dt / 3600.0f) * 1000.0f;
    if (mAhAccum > 60000.0f) mAhAccum = 0.0f;
    d.consumption = (uint16_t)mAhAccum;
}

void setup()
{
    Serial.begin(115200);
    delay(500);
    randomSeed(analogRead(0));
    SerialBT.begin(BT_DEVICE_NAME);
    Serial.println("# SIMULATOR online - synthesizing 2 drive + 1 weapon ESC");
}

void loop()
{
    const unsigned long now = millis();
    if (now - lastSend < SEND_INTERVAL_MS) return;
    const float dt = (now - lastSend) / 1000.0f;
    lastSend = now;
    const float t = now / 1000.0f;

    const float base  = 0.5f + 0.4f * sinf(t * 0.8f);
    const float steer = sinf(t * 0.35f);
#if SEND_RIGHT
    fillDrive(simR, base + 0.35f * steer, mAhR, dt); sendFrame('R', simR);
#endif
#if SEND_LEFT
    fillDrive(simL, base - 0.35f * steer, mAhL, dt); sendFrame('L', simL);
#endif

#if SEND_WEAPON
    const float phase = fmodf(t, 12.0f);
    float wt;
    if      (phase < 2.0f) wt = phase / 2.0f;
    else if (phase < 8.0f) wt = 0.92f + 0.05f * sinf(t * 4.0f);
    else                   wt = 1.0f - (phase - 8.0f) / 4.0f;
    fillWeapon(simW, wt, mAhW, dt); sendFrame('W', simW);
#endif
}
)FW";
    }

} // namespace Workspace
