// L02ModuleReloadSelfTest.cpp — WO-07 (2D stability): the editor game-module reload
// acceptance (L02), driven inside the REAL Starforge editor.
//
// This is the SECOND DLL lifecycle (distinct from the Application runtime plugin
// L01 covers): StarforgeApp::BuildScripts -> BuildRunner (real cmake configure +
// build of the scaffolded project) -> StarforgeApp::ReloadModule -> GameModule
// (serialize edit scene, stop Play, clear selection/undo, Scene.reset() while the
// OLD module is still mapped, FreeLibrary, LoadLibrary the NEW _hotN DLL, restore).
//
// When armed by COSMIC_L02_SELFTEST=<result-file> the harness, from inside the
// editor:
//   1. scaffolds a REAL project through the editor's own NewProjectAt (the shipped
//      template: CMakeLists + src/ + scenes/Main.cscene), then adds a custom
//      REFLECTED component (CS_COMPONENT L02Component) and a script (L02Script);
//   2. runs N build cycles. EVERY cycle rewrites Module.cpp (a fresh build stamp the
//      harness reads back from the loaded DLL, so an unchanged DLL can never pass)
//      and, on a fixed schedule, changes the reflected surface — add / remove /
//      rename / retype a field, change a default, add / remove a whole component
//      type (13 variants => 12 reflected-field changes across the run);
//   3. after every successful reload it asserts, through the REFLECTION registry
//      (not the serializer under test): the preserved field values equal the
//      harness's own expectation table, new fields read the new module's default,
//      the descriptor field list equals the variant EXACTLY (no accumulation, no
//      loss), the script descriptor matches, the probe entity's UUID/Tag/Transform
//      survived, Play is stopped, selection + undo are cleared, the old DLL was
//      still mapped when the module-typed destructors ran (report stamped from the
//      DLL's own destructor) and unmapped afterwards, and the new DLL is the one
//      just built;
//   4. includes one deliberate COMPILE failure and one deliberate MODULE-LOAD
//      failure (a DLL that builds but exports no CosmicModule_Register) — the
//      editor must keep the current module / keep the scene data and stay live;
//   5. saves the scene through the real Save path so the runner wrapper can parse
//      Main.cscene OUT OF PROCESS (an independent oracle) against the expected
//      final values the harness writes next to the result.
//
// Verdict -> exit code (the acceptance runner's oracle): PASS -> graceful close,
// main() returns 0; FAIL -> quick_exit(1). A JSON result is always written.

#include "StarforgeApp.h"
#include "commands/EditorCommands.h"

#include <Cosmic.h>
#include "layers/WorkspaceLayer.h"
#include <imgui.h>

#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#ifndef NOMINMAX
#define NOMINMAX
#endif
#include <windows.h>

#include <atomic>
#include <chrono>
#include <cstdarg>
#include <cstdio>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <map>
#include <sstream>
#include <string>
#include <vector>
#if defined(_DEBUG)
#include <crtdbg.h>
#endif

namespace fs = std::filesystem;

namespace Starforge
{
    namespace
    {
        // ------------------------------------------------------------------
        // The exe-side view of the report the generated module writes into.
        // The module gets the SAME definition (kReportHeader below, written into
        // the project as src/l02/L02Report.h). structSize is the drift guard:
        // the module stores its sizeof on first stamp; the harness compares.
        // ------------------------------------------------------------------
        struct L02Report
        {
            std::atomic<long long> seq{0};
            std::atomic<long long> seqLastDtor{0};
            std::atomic<long long> dtorCalls{0};
            std::atomic<long long> structSize{0};
        };

        const char* kReportHeader = R"(#pragma once
// L02Report.h — generated by the WO-07 L02 harness. Exe-owned report the module's
// component destructor stamps into (pointer handed over by COSMIC_L02_REPORT).
#include <atomic>
#include <cstdlib>
struct L02Report
{
    std::atomic<long long> seq{0};
    std::atomic<long long> seqLastDtor{0};
    std::atomic<long long> dtorCalls{0};
    std::atomic<long long> structSize{0};
};
inline L02Report* L02_Report()
{
    static L02Report* r = []() -> L02Report* {
        char* v = nullptr; size_t n = 0;
        _dupenv_s(&v, &n, "COSMIC_L02_REPORT");
        L02Report* p = v ? reinterpret_cast<L02Report*>(_strtoui64(v, nullptr, 16)) : nullptr;
        free(v);
        return p;
    }();
    return r;
}
inline void L02_StampDtor()
{
    if (L02Report* r = L02_Report())
    {
        r->structSize = (long long)sizeof(L02Report);
        ++r->dtorCalls;
        r->seqLastDtor = ++r->seq;
    }
}
)";

        // ------------------------------------------------------------------
        // Reflected-surface variants. One field change per transition.
        // ------------------------------------------------------------------
        using Cosmic::Reflect::FieldKind;
        using Cosmic::Reflect::FieldValue;

        struct FieldSpec
        {
            const char* name;
            FieldKind   kind;
            const char* cxxType;
            const char* cxxDefault;   // C++ initializer text
            FieldValue  def;          // the same default, as the harness expects it
        };
        struct Variant
        {
            const char* label;                 // what changed vs. the previous variant
            std::vector<FieldSpec> comp;       // L02Component
            std::vector<FieldSpec> extra;      // L02Extra (empty == type absent)
            std::vector<FieldSpec> script;     // L02Script
        };

        // C++ float literal text: "%g" alone yields "1f" for integral values, which is not a literal.
        std::string Lit(float v) { char b[64]; std::snprintf(b, sizeof(b), "%g", v); std::string s = b; if (s.find_first_of(".e") == std::string::npos) s += ".0"; return s + "f"; }
        FieldSpec F(const char* n, float v)             { std::string b = Lit(v); return { n, FieldKind::Float,  "float",       _strdup(b.c_str()), FieldValue{ v } }; }
        FieldSpec I(const char* n, int v)               { char b[64]; std::snprintf(b, sizeof(b), "%d", v);  return { n, FieldKind::Int32,  "int",         _strdup(b), FieldValue{ (int32_t)v } }; }
        FieldSpec B(const char* n, bool v)              { return { n, FieldKind::Bool,   "bool",        v ? "true" : "false", FieldValue{ v } }; }
        FieldSpec S(const char* n, const char* v)       { char b[96]; std::snprintf(b, sizeof(b), "\"%s\"", v); return { n, FieldKind::String, "std::string", _strdup(b), FieldValue{ std::string(v) } }; }
        FieldSpec V3(const char* n, float x, float y, float z) { std::string b = "{" + Lit(x) + ", " + Lit(y) + ", " + Lit(z) + "}"; return { n, FieldKind::Vec3, "glm::vec3", _strdup(b.c_str()), FieldValue{ glm::vec3(x, y, z) } }; }
        FieldSpec V4(const char* n, float x, float y, float z, float w) { std::string b = "{" + Lit(x) + ", " + Lit(y) + ", " + Lit(z) + ", " + Lit(w) + "}"; return { n, FieldKind::Vec4, "glm::vec4", _strdup(b.c_str()), FieldValue{ glm::vec4(x, y, z, w) } }; }

        std::vector<Variant> BuildVariants()
        {
            std::vector<Variant> v;
            const std::vector<FieldSpec> s0 = { F("Rate", 1.0f), I("Loops", 2) };
            const std::vector<FieldSpec> s1 = { F("Rate", 1.0f), I("Loops", 2), F("Bias", 0.25f) };
            const std::vector<FieldSpec> s2 = { F("Rate", 1.0f), F("Bias", 0.25f) };
            // V0: baseline
            v.push_back({ "baseline", { F("Speed", 1.5f), I("Count", 3), B("Enabled", true), S("Label", "alpha"), V3("Offset", 1, 2, 3) }, {}, s0 });
            // V1: add float Mass
            v.push_back({ "add field Mass:float", { F("Speed", 1.5f), I("Count", 3), B("Enabled", true), S("Label", "alpha"), V3("Offset", 1, 2, 3), F("Mass", 2.0f) }, {}, s0 });
            // V2: retype Count int -> float
            v.push_back({ "retype Count int->float", { F("Speed", 1.5f), F("Count", 3.0f), B("Enabled", true), S("Label", "alpha"), V3("Offset", 1, 2, 3), F("Mass", 2.0f) }, {}, s0 });
            // V3: rename Label -> Name (new default "beta")
            v.push_back({ "rename Label->Name", { F("Speed", 1.5f), F("Count", 3.0f), B("Enabled", true), S("Name", "beta"), V3("Offset", 1, 2, 3), F("Mass", 2.0f) }, {}, s0 });
            // V4: remove Offset
            v.push_back({ "remove field Offset", { F("Speed", 1.5f), F("Count", 3.0f), B("Enabled", true), S("Name", "beta"), F("Mass", 2.0f) }, {}, s0 });
            // V5: add vec4 Tint + script gains Bias
            v.push_back({ "add field Tint:vec4 + script field Bias", { F("Speed", 1.5f), F("Count", 3.0f), B("Enabled", true), S("Name", "beta"), F("Mass", 2.0f), V4("Tint", 1, 0, 0, 1) }, {}, s1 });
            // V6: default changes (Enabled true->false, Mass 2->4)
            v.push_back({ "change defaults Enabled->false, Mass->4", { F("Speed", 1.5f), F("Count", 3.0f), B("Enabled", false), S("Name", "beta"), F("Mass", 4.0f), V4("Tint", 1, 0, 0, 1) }, {}, s1 });
            // V7: add int Extra
            v.push_back({ "add field Extra:int", { F("Speed", 1.5f), F("Count", 3.0f), B("Enabled", false), S("Name", "beta"), F("Mass", 4.0f), V4("Tint", 1, 0, 0, 1), I("Extra", 7) }, {}, s1 });
            // V8: remove Mass
            v.push_back({ "remove field Mass", { F("Speed", 1.5f), F("Count", 3.0f), B("Enabled", false), S("Name", "beta"), V4("Tint", 1, 0, 0, 1), I("Extra", 7) }, {}, s1 });
            // V9: retype Speed float -> int + script loses Loops
            v.push_back({ "retype Speed float->int + script remove Loops", { I("Speed", 2), F("Count", 3.0f), B("Enabled", false), S("Name", "beta"), V4("Tint", 1, 0, 0, 1), I("Extra", 7) }, {}, s2 });
            // V10: add a second component type L02Extra
            v.push_back({ "add component type L02Extra", { I("Speed", 2), F("Count", 3.0f), B("Enabled", false), S("Name", "beta"), V4("Tint", 1, 0, 0, 1), I("Extra", 7) }, { F("Gain", 0.5f), I("Mode", 1) }, s2 });
            // V11: Name default -> "gamma", remove Tint
            v.push_back({ "change default Name->gamma + remove field Tint", { I("Speed", 2), F("Count", 3.0f), B("Enabled", false), S("Name", "gamma"), I("Extra", 7) }, { F("Gain", 0.5f), I("Mode", 1) }, s2 });
            // V12: remove component type L02Extra
            v.push_back({ "remove component type L02Extra", { I("Speed", 2), F("Count", 3.0f), B("Enabled", false), S("Name", "gamma"), I("Extra", 7) }, {}, s2 });
            return v;
        }

        // Which variant a cycle uses; 4 cycles per variant so every transition is
        // reloaded several times after the change (13 variants x 4 = 52 cycles).
        int VariantFor(int cycle, int variantCount) { const int v = (cycle - 1) / 4; return v < variantCount ? v : variantCount - 1; }

        // Failure cycles (overridable through COSMIC_L02_COMPILEFAIL_CYCLE / _LOADFAIL_CYCLE so
        // a short failing-before run can reach them early).
        int kCompileFailCycle = 25;   // deliberate syntax error
        int kLoadFailCycle    = 41;   // builds, but exports no CosmicModule_Register

        // Harness-set values for the probe instance (cycle 0, through the real
        // Commands::SetField). Everything else on the instance is a module default.
        const float kSpeed0 = 2.25f; const int kCount0 = 9; const bool kEnabled0 = false;
        const char* kLabel0 = "probe-label"; const glm::vec3 kOffset0{ 4.0f, 5.0f, 6.0f };
        const glm::vec3 kPos0{ 7.0f, 8.0f, 9.0f };
        const float kRate0 = 3.5f; const int kLoops0 = 5;

        std::string FmtValue(const FieldValue& v)
        {
            char b[128];
            if (auto p = std::get_if<bool>(&v))          std::snprintf(b, sizeof(b), "%s", *p ? "true" : "false");
            else if (auto p = std::get_if<int32_t>(&v))  std::snprintf(b, sizeof(b), "%d", *p);
            else if (auto p = std::get_if<uint32_t>(&v)) std::snprintf(b, sizeof(b), "%u", *p);
            else if (auto p = std::get_if<uint64_t>(&v)) std::snprintf(b, sizeof(b), "%llu", (unsigned long long)*p);
            else if (auto p = std::get_if<float>(&v))    std::snprintf(b, sizeof(b), "%g", *p);
            else if (auto p = std::get_if<glm::vec2>(&v)) std::snprintf(b, sizeof(b), "[%g,%g]", p->x, p->y);
            else if (auto p = std::get_if<glm::vec3>(&v)) std::snprintf(b, sizeof(b), "[%g,%g,%g]", p->x, p->y, p->z);
            else if (auto p = std::get_if<glm::vec4>(&v)) std::snprintf(b, sizeof(b), "[%g,%g,%g,%g]", p->x, p->y, p->z, p->w);
            else if (auto p = std::get_if<glm::quat>(&v)) std::snprintf(b, sizeof(b), "[%g,%g,%g,%g]", p->w, p->x, p->y, p->z);
            else if (auto p = std::get_if<std::string>(&v)) std::snprintf(b, sizeof(b), "\"%s\"", p->c_str());
            else std::snprintf(b, sizeof(b), "?");
            return b;
        }
        std::string JsonValue(const FieldValue& v)
        {
            if (auto p = std::get_if<std::string>(&v)) return "\"" + *p + "\"";
            return FmtValue(v);
        }
        bool SameValue(const FieldValue& a, const FieldValue& b)
        {
            if (a.index() != b.index()) return false;
            if (auto p = std::get_if<float>(&a)) return std::fabs(*p - std::get<float>(b)) <= 1e-6f + 1e-5f * std::fabs(std::get<float>(b));
            if (auto p = std::get_if<glm::vec3>(&a)) return glm::all(glm::epsilonEqual(*p, std::get<glm::vec3>(b), 1e-6f));
            if (auto p = std::get_if<glm::vec4>(&a)) return glm::all(glm::epsilonEqual(*p, std::get<glm::vec4>(b), 1e-6f));
            return a == b;
        }
        // Convert a stored value to a retyped field the way the serializer does
        // (JSON number -> new kind). Only float<->int retypes occur in the variants.
        FieldValue Convert(const FieldValue& v, FieldKind to)
        {
            if (to == FieldKind::Float && std::holds_alternative<int32_t>(v)) return FieldValue{ (float)std::get<int32_t>(v) };
            if (to == FieldKind::Int32 && std::holds_alternative<float>(v))   return FieldValue{ (int32_t)std::get<float>(v) };
            return v;
        }
        std::string ReadFile(const fs::path& p)
        {
            std::ifstream in(p, std::ios::binary); std::stringstream ss; ss << in.rdbuf(); return ss.str();
        }
        bool WriteFile(const fs::path& p, const std::string& text)
        {
            std::error_code ec; fs::create_directories(p.parent_path(), ec);
            std::ofstream out(p, std::ios::binary | std::ios::trunc); out << text; return (bool)out;
        }
        std::string Esc(const std::string& s)
        {
            std::string o; for (char c : s) { if (c == '"' || c == '\\') o += '\\'; if (c == '\n') { o += "\\n"; continue; } o += c; } return o;
        }
    }

    // =====================================================================
    // State
    // =====================================================================
    struct StarforgeApp::L02ReloadSelfTest
    {
        enum Phase { Boot, StartCycle, Building, Verify, Finish, Done };

        std::string resultPath, projectRoot, projectDir, moduleName = "L02Reload";
        int   cyclesPlanned = 52;              // 50 successful + 1 compile-fail + 1 load-fail
        Phase phase = Boot;
        int   cycle = 0;                       // 1-based; 0 == the initial load
        int   bootFrames = 0, buildFrames = 0;
        std::chrono::steady_clock::time_point cycleStart, runStart = std::chrono::steady_clock::now();
        std::vector<Variant> variants = BuildVariants();
        std::string templateModuleCpp;         // the REAL scaffolded Module.cpp (template output)

        // expectation table for the probe instance (name -> value), per component
        std::map<std::string, FieldValue> expComp, expExtra, expScript;
        int prevVariant = -1;
        bool extraPresent = false;             // L02Extra type currently in the module
        bool extraOpaqueExpected = false;      // the block should survive opaquely
        bool playedDuringBuild = false, undoDuringBuild = false;

        Cosmic::UUID probeId;
        L02Report report;

        // probes stamped by ReloadModule (via the StarforgeApp hooks)
        long long seqSceneDropped = 0, seqUnloaded = 0, seqLoaded = 0;
        int  oldStillLoadedAtDrop = -1, oldGoneAfterUnload = -1;
        int  reloadCalls = 0; bool lastLoadOk = false; std::string lastOldStem;
        long long dtorCallsAtCycleStart = 0;
        int  hotBefore = 0; int builderTransitions = 0;

        // results
        int successful = 0, reflectedChanges = 0, failures = 0, failedCycles = 0;
        bool compileFailSeen = false, loadFailSeen = false;
        std::vector<std::string> log, cycles;
        std::vector<std::string> checks;       // failing check descriptions

        void note(const char* fmt, ...)
        {
            char buf[512]; va_list ap; va_start(ap, fmt); _vsnprintf_s(buf, sizeof(buf), _TRUNCATE, fmt, ap); va_end(ap);
            log.emplace_back(buf); std::printf("[L02] %s\n", buf); std::fflush(stdout);
        }
        void fail(const char* fmt, ...)
        {
            char buf[512]; va_list ap; va_start(ap, fmt); _vsnprintf_s(buf, sizeof(buf), _TRUNCATE, fmt, ap); va_end(ap);
            ++failures; checks.emplace_back(std::string("cycle ") + std::to_string(cycle) + ": " + buf);
            log.emplace_back(std::string("FAIL ") + buf); std::printf("[L02] FAIL %s\n", buf); std::fflush(stdout);
        }
    };

    // =====================================================================
    // Source generation (the "edit" half of edit -> rebuild -> reload)
    // =====================================================================
    namespace
    {
        std::string GenComponentHeader(const Variant& v, int cycle)
        {
            std::string s;
            s += "#pragma once\n// L02Component.h — generated by the WO-07 L02 harness (cycle " + std::to_string(cycle) + ": " + v.label + ").\n";
            s += "#include <Cosmic.h>\n#include \"L02Report.h\"\n#include <string>\n\n";
            s += "struct L02Component\n{\n";
            for (const auto& f : v.comp) s += std::string("    ") + f.cxxType + " " + f.name + " = " + f.cxxDefault + ";\n";
            s += "    L02Component() = default;\n    L02Component(const L02Component&) = default;\n    L02Component& operator=(const L02Component&) = default;\n";
            s += "    ~L02Component() { L02_StampDtor(); }   // module-typed destructor: must run while this DLL is mapped\n};\n";
            s += "CS_REGISTER_COMPONENT(L02Component)\n\n";
            if (!v.extra.empty())
            {
                s += "struct L02Extra\n{\n";
                for (const auto& f : v.extra) s += std::string("    ") + f.cxxType + " " + f.name + " = " + f.cxxDefault + ";\n";
                s += "};\nCS_REGISTER_COMPONENT(L02Extra)\n\n";
            }
            s += "class L02Script : public Cosmic::ScriptableEntity\n{\npublic:\n";
            for (const auto& f : v.script) s += std::string("    ") + f.cxxType + " " + f.name + " = " + f.cxxDefault + ";\n";
            s += "protected:\n    void OnUpdate(float) override\n    {\n        // Drifts the RUNTIME entity every frame: proves a reload while playing\n        // restores the EDIT scene, not the simulated one.\n";
            s += "        GetComponent<Cosmic::TransformComponent>().Position.x += 1.0f;\n    }\n};\n";
            return s;
        }

        std::string GenModuleCpp(const std::string& templateCpp, const Variant& v, int cycle, bool compileError, bool noExports)
        {
            // Keep the REAL template Module.cpp (its script registrations are the
            // shipped content); splice the L02 include + block in, and stamp the cycle.
            std::string s = templateCpp;
            const std::string inc = "#include <Cosmic.h>";
            size_t p = s.find(inc);
            if (p != std::string::npos)
                s.insert(p + inc.size(), "\n#include \"l02/L02Component.h\"   // WO-07 L02 harness");
            std::string block;
            block += "    // ---- WO-07 L02 harness (cycle " + std::to_string(cycle) + ", variant: " + v.label + ") ----\n";
            block += "    CS_COMPONENT(L02Component)\n";
            for (const auto& f : v.comp) block += std::string("        CS_FIELD(") + f.name + ")\n";
            block += "    CS_END;\n";
            if (!v.extra.empty())
            {
                block += "    CS_COMPONENT(L02Extra)\n";
                for (const auto& f : v.extra) block += std::string("        CS_FIELD(") + f.name + ")\n";
                block += "    CS_END;\n";
            }
            block += "    CS_SCRIPT(L02Script)\n";
            for (const auto& f : v.script) block += std::string("        CS_FIELD(") + f.name + ")\n";
            block += "    CS_END;\n";
            if (compileError)
                block += "    this is a deliberate WO-07 L02 compile error;\n";
            const std::string endTok = "CS_MODULE_END()";
            p = s.rfind(endTok);
            if (p != std::string::npos)
                s.insert(p, block);
            if (noExports)
            {
                // A DLL that BUILDS but exports none of the module signatures: strip the
                // CS_MODULE_BEGIN/END wrapper into a plain (unexported) function.
                size_t b = s.find("CS_MODULE_BEGIN(");
                size_t e = s.rfind(endTok);
                if (b != std::string::npos && e != std::string::npos)
                {
                    const size_t bEnd = s.find(')', b);
                    s.replace(e, endTok.size(), "}");
                    s.replace(b, bEnd + 1 - b, "static void L02_UnexportedRegister(::Cosmic::ModuleRegistry& reg)\n{\n    reg.BeginModule(\"L02Reload\");");
                    // CS_MODULE_END also emitted reg.EndModule(); keep the function well-formed:
                    s.insert(s.rfind('}'), "    reg.EndModule();\n");
                }
            }
            s += "\n// build stamp: the harness reads this back from the LOADED dll, so an unchanged\n// binary cannot pass as a rebuild.\n";
            s += "extern \"C\" __declspec(dllexport) int L02_BuildStamp() { return " + std::to_string(cycle) + "; }\n";
            return s;
        }
    }

    // =====================================================================
    // Hooks
    // =====================================================================
    void StarforgeApp::L02SelfTestInit()
    {
        const char* rp = std::getenv("COSMIC_L02_SELFTEST");
        if (!rp || !*rp)
            return;
        m_L02 = new L02ReloadSelfTest();
        auto& t = *m_L02;
        t.resultPath = rp;
        if (const char* root = std::getenv("COSMIC_L02_PROJECT_ROOT")) t.projectRoot = root;
        if (const char* n = std::getenv("COSMIC_L02_CYCLES")) t.cyclesPlanned = std::atoi(n);
        if (const char* n = std::getenv("COSMIC_L02_COMPILEFAIL_CYCLE")) kCompileFailCycle = std::atoi(n);
        if (const char* n = std::getenv("COSMIC_L02_LOADFAIL_CYCLE"))    kLoadFailCycle    = std::atoi(n);
        if (t.projectRoot.empty()) t.projectRoot = (fs::current_path() / "l02-projects").generic_string();

#if defined(_DEBUG)
        _CrtSetReportMode(_CRT_ASSERT, _CRTDBG_MODE_FILE);
        _CrtSetReportFile(_CRT_ASSERT, _CRTDBG_FILE_STDERR);
        _set_abort_behavior(0, _WRITE_ABORT_MSG | _CALL_REPORTFAULT);
#endif
        SetErrorMode(SEM_NOGPFAULTERRORBOX | SEM_FAILCRITICALERRORS | SEM_NOOPENFILEERRORBOX);
        m_OpenFirstRun = false;
        Cosmic::Application::Get().GetWindow().SetVSync(false);

        // Hand the exe-owned report to every module build (read by L02_Report()).
        char ptr[32]; std::snprintf(ptr, sizeof(ptr), "%llX", (unsigned long long)(uintptr_t)&t.report);
        _putenv_s("COSMIC_L02_REPORT", ptr);

        t.note("armed: result=%s projectRoot=%s cycles=%d sdk=%s", rp, t.projectRoot.c_str(), t.cyclesPlanned, SdkDir().c_str());
    }

    void StarforgeApp::L02SelfTestShutdown()
    {
        delete m_L02; m_L02 = nullptr;
    }

    // ReloadModule probes — stamp the destruction-order proof from the real path.
    void StarforgeApp::L02SelfTestOnSceneDropped(const std::string& oldStem)
    {
        if (!m_L02) return;
        auto& t = *m_L02;
        ++t.reloadCalls; t.lastOldStem = oldStem;
        t.seqSceneDropped = ++t.report.seq;
        t.oldStillLoadedAtDrop = oldStem.empty() ? -1 : (GetModuleHandleA((oldStem + ".dll").c_str()) != nullptr ? 1 : 0);
    }
    void StarforgeApp::L02SelfTestOnModuleUnloaded(const std::string& oldStem)
    {
        if (!m_L02) return;
        auto& t = *m_L02;
        t.seqUnloaded = ++t.report.seq;
        t.oldGoneAfterUnload = oldStem.empty() ? -1 : (GetModuleHandleA((oldStem + ".dll").c_str()) == nullptr ? 1 : 0);
    }
    void StarforgeApp::L02SelfTestOnModuleLoaded(bool ok)
    {
        if (!m_L02) return;
        m_L02->seqLoaded = ++m_L02->report.seq;
        m_L02->lastLoadOk = ok;
    }

    // =====================================================================
    // The per-frame driver (runs right after the build pump in OnUpdate)
    // =====================================================================
    namespace
    {
        Cosmic::Entity FindProbe(Cosmic::Scene& scene, Cosmic::UUID id) { return scene.FindByUUID(id); }
    }

    void StarforgeApp::L02SelfTestTick()
    {
        if (!m_L02) return;
        auto& t = *m_L02;
        using P = L02ReloadSelfTest;
        auto& registry = Cosmic::Reflect::GetRegistry();

        switch (t.phase)
        {
        case P::Boot:
        {
            if (++t.bootFrames < 5) return;   // let the workspace settle a few frames
            // 1) A REAL project through the editor's own scaffold + open path.
            std::error_code ec; fs::create_directories(t.projectRoot, ec);
            if (!NewProjectAt(t.moduleName, t.projectRoot)) { t.fail("NewProjectAt failed (templates missing?)"); t.phase = P::Finish; return; }
            t.projectDir = ProjectDir();
            if (!ProjectIsScaffolded()) { t.fail("scaffolded project has no CMakeLists.txt"); t.phase = P::Finish; return; }
            t.templateModuleCpp = ReadFile(fs::path(t.projectDir) / "src" / "Module.cpp");
            if (t.templateModuleCpp.find("CS_MODULE_END()") == std::string::npos) { t.fail("template Module.cpp not recognised"); t.phase = P::Finish; return; }
            WriteFile(fs::path(t.projectDir) / "src" / "l02" / "L02Report.h", kReportHeader);
            t.note("scaffolded real project at %s (module '%s'), template Module.cpp %zu bytes", t.projectDir.c_str(), t.moduleName.c_str(), t.templateModuleCpp.size());
            // 2) Cycle 0: the initial build + load of variant 0 (no reload yet).
            t.cycle = 0;
            t.phase = P::StartCycle;
            return;
        }

        case P::StartCycle:
        {
            const int v = t.cycle == 0 ? 0 : VariantFor(t.cycle, (int)t.variants.size());
            const Variant& var = t.variants[v];
            const bool compileFail = t.cycle == kCompileFailCycle;
            const bool loadFail    = t.cycle == kLoadFailCycle;
            // Edit the sources (every cycle stamps a new build number).
            WriteFile(fs::path(t.projectDir) / "src" / "l02" / "L02Component.h", GenComponentHeader(var, t.cycle));
            WriteFile(fs::path(t.projectDir) / "src" / "Module.cpp", GenModuleCpp(t.templateModuleCpp, var, t.cycle, compileFail, loadFail));
            if (t.cycle > 0 && !compileFail && !loadFail && v != t.prevVariant)
            {
                ++t.reflectedChanges;
                // Roll the expectation table forward across the reflected change:
                // kept fields keep their value (retyped ones convert), new ones take
                // the NEW module's default, removed ones vanish.
                auto roll = [](std::map<std::string, FieldValue>& exp, const std::vector<FieldSpec>& spec)
                {
                    std::map<std::string, FieldValue> next;
                    for (const auto& f : spec)
                    {
                        auto it = exp.find(f.name);
                        next[f.name] = it == exp.end() ? f.def : Convert(it->second, f.kind);
                    }
                    exp.swap(next);
                };
                roll(t.expComp, var.comp);
                roll(t.expScript, var.script);
                if (!var.extra.empty() && !t.extraPresent)
                {
                    // Type appears: the probe gets the component added (below, after
                    // reload) so its block exists for the later removal to preserve.
                    t.expExtra.clear();
                    for (const auto& f : var.extra) t.expExtra[f.name] = f.def;
                }
                if (var.extra.empty() && t.extraPresent)
                    t.extraOpaqueExpected = true;   // block must survive as an opaque (C05) block
                t.note("cycle %d: reflected change #%d -> variant %d (%s)", t.cycle, t.reflectedChanges, v, var.label);
            }
            t.prevVariant = (compileFail || loadFail) ? t.prevVariant : v;
            t.hotBefore = m_HotCounter;
            t.dtorCallsAtCycleStart = t.report.dtorCalls.load();
            t.seqSceneDropped = t.seqUnloaded = t.seqLoaded = 0; t.oldStillLoadedAtDrop = t.oldGoneAfterUnload = -1;
            t.playedDuringBuild = t.undoDuringBuild = false;
            t.buildFrames = 0;
            t.cycleStart = std::chrono::steady_clock::now();
            const int reloadsBefore = t.reloadCalls;
            BuildScripts();                            // the REAL editor build path
            if (!m_Builder.IsBuilding() || m_HotCounter != t.hotBefore + 1)
            {
                t.fail("BuildScripts() did not start a build (hot %d->%d)", t.hotBefore, m_HotCounter);
                t.phase = P::Finish; return;
            }
            (void)reloadsBefore;
            t.note("cycle %d: building %s (%s%s)", t.cycle, m_LastBuiltStem.c_str(), var.label,
                   compileFail ? ", DELIBERATE COMPILE ERROR" : loadFail ? ", DELIBERATE NO-EXPORT DLL" : "");
            t.phase = P::Building;
            return;
        }

        case P::Building:
        {
            ++t.buildFrames;
            // While the compiler runs, exercise the states the reload must clear.
            if (t.cycle > 0 && t.buildFrames == 3 && (t.cycle % 5) == 2 && !IsPlaying())
            {
                PlayScene();                            // Play DURING a build is allowed by the editor
                t.playedDuringBuild = IsPlaying();
                if (!t.playedDuringBuild) t.fail("PlayScene() did not enter Play");
            }
            if (t.cycle > 0 && t.buildFrames == 3 && (t.cycle % 5) == 3 && m_Ctx.Scene)
            {
                if (Cosmic::Entity e = FindProbe(*m_Ctx.Scene, t.probeId))
                {
                    m_Ctx.SelectOnly(e);
                    if (const auto* d = registry.FindByName("L02Component"))
                    {
                        const auto it = t.expComp.begin();   // a same-value edit still records undo
                        Commands::SetField(m_Ctx, e, d->TypeId, it->first, it->second);
                    }
                    t.undoDuringBuild = m_Ctx.Commands.CanUndo() && m_Ctx.HasSelection();
                    if (!t.undoDuringBuild) t.fail("could not stage selection + undo during the build");
                }
            }
            if (m_Builder.IsBuilding())
            {
                const double secs = std::chrono::duration<double>(std::chrono::steady_clock::now() - t.cycleStart).count();
                if (secs > 300.0) { t.fail("build exceeded 300 s"); t.phase = P::Finish; }
                return;
            }
            // Build finished this frame: the pump already delivered onDone (ReloadModule ran).
            t.phase = P::Verify;
            return;
        }

        case P::Verify:
        {
            const double secs = std::chrono::duration<double>(std::chrono::steady_clock::now() - t.cycleStart).count();
            const int v = t.cycle == 0 ? 0 : VariantFor(t.cycle, (int)t.variants.size());
            const Variant& var = t.variants[v];
            const bool compileFail = t.cycle == kCompileFailCycle;
            const bool loadFail    = t.cycle == kLoadFailCycle;
            const auto status = m_Builder.GetStatus();
            const int failuresBefore = t.failures;
            std::string rec = "{ \"cycle\": " + std::to_string(t.cycle) + ", \"variant\": " + std::to_string(v) +
                              ", \"stem\": \"" + m_LastBuiltStem + "\", \"seconds\": " + std::to_string(secs);

            if (compileFail)
            {
                // The editor must report the failure and KEEP the current module + scene.
                if (status != BuildRunner::Status::Failed) t.fail("compile-error cycle: builder status %d, expected Failed", (int)status);
                if (!m_Module.IsLoaded() || m_Module.DllStem() == m_LastBuiltStem) t.fail("compile-error cycle: module changed (%s)", m_Module.DllStem().c_str());
                if (!m_Ctx.Scene) t.fail("compile-error cycle: scene gone");
                bool logged = false;
                for (const auto& l : m_Ctx.ConsoleLines) if (l.Text.find("[Build] Failed") != std::string::npos) logged = true;
                if (!logged) t.fail("compile-error cycle: no '[Build] Failed' console line");
                if (IsPlaying())
                {
                    // A failed build keeps EVERYTHING, Play included (correct); stop it here so
                    // the next cycle's BuildScripts is not refused.
                    t.note("compile-error cycle: Play still running (kept, as documented); harness stops it");
                    StopScene();
                }
                t.compileFailSeen = t.failures == failuresBefore;
                rec += ", \"kind\": \"compile-fail\"";
            }
            else if (loadFail)
            {
                // Builds, ReloadModule runs, GameModule::Load must reject the DLL and the
                // editor must keep the scene DATA (opaque blocks) and stay live.
                if (status != BuildRunner::Status::Success) t.fail("no-export cycle: builder status %d, expected Success", (int)status);
                if (t.reloadCalls == 0 || t.lastLoadOk) t.fail("no-export cycle: ReloadModule did not report a failed load");
                if (m_Module.IsLoaded()) t.fail("no-export cycle: a module is still loaded (%s)", m_Module.DllStem().c_str());
                bool logged = false;
                for (const auto& l : m_Ctx.ConsoleLines) if (l.Text.find("[Module] Load failed") != std::string::npos) logged = true;
                if (!logged) t.fail("no-export cycle: no '[Module] Load failed' console line");
                if (!m_Ctx.Scene) t.fail("no-export cycle: scene gone");
                else if (Cosmic::Entity e = FindProbe(*m_Ctx.Scene, t.probeId))
                {
                    // With no module, the custom blocks must have survived opaquely (C05).
                    bool opaqueComp = false;
                    if (e.HasComponent<Cosmic::OpaqueComponentsComponent>())
                        for (const auto& b : e.GetComponent<Cosmic::OpaqueComponentsComponent>().Blocks)
                            if (b.first == "L02Component") opaqueComp = true;
                    if (!opaqueComp) t.fail("no-export cycle: L02Component block was not preserved opaquely");
                    if (registry.FindByName("L02Component")) t.fail("no-export cycle: stale L02Component descriptor still registered after unload");
                }
                else t.fail("no-export cycle: probe entity lost");
                t.loadFailSeen = t.failures == failuresBefore;
                rec += ", \"kind\": \"load-fail\"";
            }
            else
            {
                if (status != BuildRunner::Status::Success) { t.fail("build did not succeed (status %d)", (int)status); }
                else
                {
                    // ---- the module that is loaded is the one just built ----
                    if (!m_Module.IsLoaded()) t.fail("no module loaded after reload");
                    if (m_Module.DllStem() != m_LastBuiltStem) t.fail("loaded stem '%s' != built '%s'", m_Module.DllStem().c_str(), m_LastBuiltStem.c_str());
                    HMODULE h = GetModuleHandleA((m_LastBuiltStem + ".dll").c_str());
                    if (!h) t.fail("%s.dll is not mapped", m_LastBuiltStem.c_str());
                    else
                    {
                        auto stamp = (int(*)())GetProcAddress(h, "L02_BuildStamp");
                        const int got = stamp ? stamp() : -1;
                        if (got != t.cycle) t.fail("build stamp %d != cycle %d (stale binary?)", got, t.cycle);
                        rec += ", \"stamp\": " + std::to_string(got);
                    }
                    if (t.report.structSize && t.report.structSize != (long long)sizeof(L02Report)) t.fail("report struct drift (%lld vs %zu)", t.report.structSize.load(), sizeof(L02Report));

                    // ---- destruction order: old code mapped while dtors ran, gone after ----
                    if (t.cycle > 0 && t.lastOldStem.empty())
                    {
                        // No module was mapped before this reload (the previous cycle was the
                        // failed load): nothing to unmap, no module-typed destructors to run.
                        if (t.reloadCalls == 0 || !t.lastLoadOk) t.fail("ReloadModule did not run / load failed");
                        t.note("cycle %d: reload from NO module (after the failed load) - destruction-order proof not applicable", t.cycle);
                    }
                    else if (t.cycle > 0)
                    {
                        if (t.reloadCalls == 0 || !t.lastLoadOk) t.fail("ReloadModule did not run / load failed");
                        if (t.oldStillLoadedAtDrop != 1) t.fail("old module %s was NOT mapped when the scene was dropped (%d)", t.lastOldStem.c_str(), t.oldStillLoadedAtDrop);
                        if (t.oldGoneAfterUnload != 1)   t.fail("old module %s still mapped after Unload (%d)", t.lastOldStem.c_str(), t.oldGoneAfterUnload);
                        if (t.report.dtorCalls <= t.dtorCallsAtCycleStart) t.fail("module-typed destructor never ran during reload");
                        if (!(t.report.seqLastDtor < t.seqSceneDropped && t.seqSceneDropped < t.seqUnloaded && t.seqUnloaded < t.seqLoaded))
                            t.fail("ordering violated: lastDtor=%lld sceneDropped=%lld unloaded=%lld loaded=%lld",
                                   t.report.seqLastDtor.load(), t.seqSceneDropped, t.seqUnloaded, t.seqLoaded);
                        if (GetModuleHandleA((t.lastOldStem + ".dll").c_str())) t.fail("old module %s still mapped after reload", t.lastOldStem.c_str());
                    }

                    // ---- registry: exactly the variant, no accumulation, no loss ----
                    auto checkDesc = [&](const char* name, const std::vector<FieldSpec>& spec, const Cosmic::Reflect::TypeDescriptor* d)
                    {
                        if (!d) { t.fail("descriptor '%s' missing", name); return; }
                        if (d->Fields.size() != spec.size())
                        {
                            std::string names; for (const auto& f : d->Fields) names += f.Name + " ";
                            t.fail("descriptor '%s' has %zu fields, expected %zu [%s]", name, d->Fields.size(), spec.size(), names.c_str());
                            return;
                        }
                        for (size_t i = 0; i < spec.size(); ++i)
                            if (d->Fields[i].Name != spec[i].name || d->Fields[i].Kind != spec[i].kind)
                                t.fail("descriptor '%s' field %zu is %s/%d, expected %s/%d", name, i, d->Fields[i].Name.c_str(), (int)d->Fields[i].Kind, spec[i].name, (int)spec[i].kind);
                    };
                    const auto* dComp  = registry.FindByName("L02Component");
                    const auto* dExtra = registry.FindByName("L02Extra");
                    checkDesc("L02Component", var.comp, dComp);
                    if (!var.extra.empty()) checkDesc("L02Extra", var.extra, dExtra);
                    else if (dExtra) t.fail("L02Extra descriptor still registered after the type was removed");
                    const auto* sd = Cosmic::ModuleRegistry::Get().FindScript("L02Script");
                    if (!sd) t.fail("script L02Script not registered");
                    else
                    {
                        checkDesc("L02Script", var.script, &sd->Fields);
                        if (sd->Module != t.moduleName) t.fail("L02Script tagged with module '%s'", sd->Module.c_str());
                    }
                    const auto ids = Cosmic::ModuleRegistry::Get().ComponentTypeIds(t.moduleName);
                    const size_t expectIds = var.extra.empty() ? 1 : 2;
                    if (ids.size() != expectIds) t.fail("module notes %zu component types, expected %zu", ids.size(), expectIds);
                    const auto scripts = Cosmic::ModuleRegistry::Get().ScriptNames(t.moduleName);
                    if (scripts.size() < 2) t.fail("module registers %zu scripts (template scripts missing?)", scripts.size());
                    rec += ", \"compFields\": " + std::to_string(dComp ? dComp->Fields.size() : 0) + ", \"scripts\": " + std::to_string(scripts.size());

                    // ---- the new module's DEFAULTS resolve (fresh instance, reflection read) ----
                    if (dComp && m_Ctx.Scene)
                    {
                        Cosmic::Entity tmp = m_Ctx.Scene->CreateEntity("L02Tmp");
                        void* c = dComp->Add(m_Ctx.Scene->GetRegistry(), (entt::entity)tmp);
                        for (const auto& f : dComp->Fields)
                        {
                            const FieldSpec* spec = nullptr;
                            for (const auto& s : var.comp) if (f.Name == s.name) spec = &s;
                            if (spec && !SameValue(f.Get(c), spec->def))
                                t.fail("default of %s = %s, expected %s", f.Name.c_str(), FmtValue(f.Get(c)).c_str(), FmtValue(spec->def).c_str());
                        }
                        m_Ctx.Scene->DestroyEntity(tmp);
                    }

                    // ---- cycle 0: create the probe instance through the REAL commands ----
                    if (t.cycle == 0 && dComp && m_Ctx.Scene)
                    {
                        Cosmic::Entity probe = Commands::Create(m_Ctx, "L02Probe", Cosmic::Entity{}, [&](Cosmic::Entity e)
                        {
                            if (!e.HasComponent<Cosmic::TransformComponent>()) e.AddComponent<Cosmic::TransformComponent>();
                            e.GetComponent<Cosmic::TransformComponent>().Position = kPos0;
                            e.AddComponent<Cosmic::NativeScriptComponent>("L02Script");
                        });
                        t.probeId = probe.GetComponent<Cosmic::IDComponent>().ID;
                        Commands::AddComponent(m_Ctx, probe, dComp->TypeId);
                        Commands::SetField(m_Ctx, probe, dComp->TypeId, "Speed",   FieldValue{ kSpeed0 });
                        Commands::SetField(m_Ctx, probe, dComp->TypeId, "Count",   FieldValue{ (int32_t)kCount0 });
                        Commands::SetField(m_Ctx, probe, dComp->TypeId, "Enabled", FieldValue{ kEnabled0 });
                        Commands::SetField(m_Ctx, probe, dComp->TypeId, "Label",   FieldValue{ std::string(kLabel0) });
                        Commands::SetField(m_Ctx, probe, dComp->TypeId, "Offset",  FieldValue{ kOffset0 });
                        auto& nsc = probe.GetComponent<Cosmic::NativeScriptComponent>();
                        nsc.Fields["Rate"]  = FieldValue{ kRate0 };
                        nsc.Fields["Loops"] = FieldValue{ (int32_t)kLoops0 };
                        t.expComp   = { { "Speed", FieldValue{ kSpeed0 } }, { "Count", FieldValue{ (int32_t)kCount0 } }, { "Enabled", FieldValue{ kEnabled0 } },
                                        { "Label", FieldValue{ std::string(kLabel0) } }, { "Offset", FieldValue{ kOffset0 } } };
                        t.expScript = { { "Rate", FieldValue{ kRate0 } }, { "Loops", FieldValue{ (int32_t)kLoops0 } } };
                        if (!m_Ctx.Commands.CanUndo()) t.fail("real commands recorded no undo");
                        t.note("cycle 0: probe entity %s created via Commands (Speed=%g Count=%d Enabled=%d Label=%s Offset=[%g,%g,%g] Pos=[%g,%g,%g])",
                               t.probeId.ToString().c_str(), kSpeed0, kCount0, kEnabled0 ? 1 : 0, kLabel0, kOffset0.x, kOffset0.y, kOffset0.z, kPos0.x, kPos0.y, kPos0.z);
                    }

                    // ---- documented rule: Play stopped, selection + undo cleared, not dirty ----
                    // (checked BEFORE the harness makes any edit of its own below)
                    if (t.cycle > 0)
                    {
                        if (IsPlaying()) t.fail("Play still active after reload");
                        if (m_Ctx.HasSelection()) t.fail("selection not cleared by reload");
                        if (m_Ctx.Commands.CanUndo() || m_Ctx.Commands.CanRedo()) t.fail("undo/redo not cleared by reload");
                        if (m_Ctx.Dirty) t.fail("scene left dirty by reload");
                    }

                    // ---- the probe instance after a reload: preserved + resolved ----
                    if (t.cycle > 0 && m_Ctx.Scene)
                    {
                        Cosmic::Entity e = FindProbe(*m_Ctx.Scene, t.probeId);
                        if (!e) t.fail("probe entity (UUID %s) lost across reload", t.probeId.ToString().c_str());
                        else
                        {
                            if (!e.HasComponent<Cosmic::TagComponent>() || e.GetComponent<Cosmic::TagComponent>().Tag != "L02Probe") t.fail("probe Tag lost");
                            const glm::vec3 pos = e.GetComponent<Cosmic::TransformComponent>().Position;
                            if (!glm::all(glm::epsilonEqual(pos, kPos0, 1e-6f)))
                                t.fail("edit-scene Position [%g,%g,%g] != [%g,%g,%g]%s", pos.x, pos.y, pos.z, kPos0.x, kPos0.y, kPos0.z,
                                       t.playedDuringBuild ? " (runtime state leaked into the edit scene)" : "");
                            if (dComp)
                            {
                                void* c = dComp->Get(m_Ctx.Scene->GetRegistry(), (entt::entity)e);
                                if (!c) t.fail("probe lost its L02Component");
                                else for (const auto& f : dComp->Fields)
                                {
                                    auto it = t.expComp.find(f.Name);
                                    if (it == t.expComp.end()) { t.fail("unexpected field %s", f.Name.c_str()); continue; }
                                    const FieldValue got = f.Get(c);
                                    if (!SameValue(got, it->second))
                                        t.fail("L02Component.%s = %s, expected %s", f.Name.c_str(), FmtValue(got).c_str(), FmtValue(it->second).c_str());
                                }
                            }
                            if (!var.extra.empty() && dExtra)
                            {
                                void* x = dExtra->Get(m_Ctx.Scene->GetRegistry(), (entt::entity)e);
                                if (!x && !t.extraPresent)
                                {
                                    // Type just appeared: attach it through the real command so the
                                    // instance (module defaults) exists for later cycles.
                                    Commands::AddComponent(m_Ctx, e, dExtra->TypeId);
                                    x = dExtra->Get(m_Ctx.Scene->GetRegistry(), (entt::entity)e);
                                    t.note("cycle %d: L02Extra attached to the probe (module defaults)", t.cycle);
                                }
                                if (!x) t.fail("probe lost its L02Extra");
                                else for (const auto& f : dExtra->Fields)
                                {
                                    auto it = t.expExtra.find(f.Name);
                                    if (it != t.expExtra.end() && !SameValue(f.Get(x), it->second))
                                        t.fail("L02Extra.%s = %s, expected %s", f.Name.c_str(), FmtValue(f.Get(x)).c_str(), FmtValue(it->second).c_str());
                                }
                                t.extraPresent = true;
                            }
                            if (var.extra.empty() && t.extraOpaqueExpected)
                            {
                                bool opaque = false;
                                if (e.HasComponent<Cosmic::OpaqueComponentsComponent>())
                                    for (const auto& b : e.GetComponent<Cosmic::OpaqueComponentsComponent>().Blocks)
                                        if (b.first == "L02Extra" && b.second.find("Gain") != std::string::npos) opaque = true;
                                if (!opaque) t.fail("removed L02Extra block was not preserved opaquely (C05)");
                                t.extraPresent = false;
                            }
                            // script: engine-owned overrides preserved; field set == variant
                            if (!e.HasComponent<Cosmic::NativeScriptComponent>()) t.fail("probe lost NativeScript");
                            else
                            {
                                const auto& nsc = e.GetComponent<Cosmic::NativeScriptComponent>();
                                if (nsc.ClassName != "L02Script") t.fail("script class '%s'", nsc.ClassName.c_str());
                                for (const auto& s : var.script)
                                {
                                    auto it = nsc.Fields.find(s.name);
                                    auto ex = t.expScript.find(s.name);
                                    if (ex == t.expScript.end()) continue;
                                    const bool isDefault = SameValue(ex->second, s.def);
                                    if (it == nsc.Fields.end()) { if (!isDefault) t.fail("script field %s override lost", s.name); }
                                    else if (!SameValue(it->second, ex->second)) t.fail("script %s = %s, expected %s", s.name, FmtValue(it->second).c_str(), FmtValue(ex->second).c_str());
                                }
                                for (const auto& kv : nsc.Fields)
                                {
                                    bool inSpec = false; for (const auto& s : var.script) if (kv.first == s.name) inSpec = true;
                                    if (!inSpec) t.fail("script override '%s' survived after the field was removed", kv.first.c_str());
                                }
                            }
                        }
                    }
                    // ---- persist through the REAL save path (out-of-process oracle input) ----
                    if (m_Ctx.Scene && !SaveScene()) t.fail("SaveScene failed");
                    if (t.failures == failuresBefore && t.cycle > 0) ++t.successful;
                    rec += std::string(", \"playedDuringBuild\": ") + (t.playedDuringBuild ? "true" : "false") +
                           ", \"undoDuringBuild\": " + (t.undoDuringBuild ? "true" : "false");
                }
                rec += ", \"kind\": \"" + std::string(t.cycle == 0 ? "initial-load" : "reload") + "\"";
            }
            rec += std::string(", \"ok\": ") + (t.failures == failuresBefore ? "true" : "false") + " }";
            t.cycles.push_back(rec);
            t.note("cycle %d done in %.1fs (%s)", t.cycle, secs, t.failures == failuresBefore ? "ok" : "FAILED");

            // Stop after the planned cycles, or once three cycles have failed (enough
            // failing-before evidence; the rest would only repeat it).
            if (t.failures > 0 && t.failures != failuresBefore) ++t.failedCycles;
            if (t.cycle >= t.cyclesPlanned || t.failedCycles >= 3 || !m_Ctx.Scene)
                t.phase = P::Finish;
            else { ++t.cycle; t.phase = P::StartCycle; }
            return;
        }

        case P::Finish:
        {
            const double total = std::chrono::duration<double>(std::chrono::steady_clock::now() - t.runStart).count();
            const bool pass = t.failures == 0 && t.successful >= 50 && t.reflectedChanges >= 10 && t.compileFailSeen && t.loadFailSeen;
#if defined(NDEBUG)
            const char* cfg = "Release";
#else
            const char* cfg = "Debug";
#endif
            // Expected final values for the OUT-OF-PROCESS oracle (parsed by the runner
            // wrapper from the saved scenes/Main.cscene, never through the serializer).
            {
                std::ofstream f(fs::path(t.resultPath).parent_path() / "l02-expected-final.json", std::ios::trunc);
                f << "{\n  \"scene\": \"" << Esc((fs::path(t.projectDir) / "scenes" / "Main.cscene").generic_string()) << "\",\n";
                f << "  \"probeId\": \"" << t.probeId.ToString() << "\",\n  \"position\": [" << kPos0.x << ", " << kPos0.y << ", " << kPos0.z << "],\n";
                f << "  \"L02Component\": {";
                bool first = true;
                for (const auto& kv : t.expComp) { f << (first ? " " : ", ") << "\"" << kv.first << "\": " << JsonValue(kv.second); first = false; }
                f << " },\n  \"L02ExtraOpaque\": " << (t.extraOpaqueExpected ? "true" : "false") << ",\n";
                f << "  \"NativeScript\": { \"ClassName\": \"L02Script\", \"Fields\": {";
                first = true;
                for (const auto& kv : t.expScript) { f << (first ? " " : ", ") << "\"" << kv.first << "\": " << JsonValue(kv.second); first = false; }
                f << " } }\n}\n";
            }
            std::ofstream f(t.resultPath, std::ios::trunc);
            if (f)
            {
                f << "{\n  \"work_order\": \"WO-07\",\n  \"case\": \"L02 editor game-module rebuild/reload\",\n  \"config\": \"" << cfg << "\",\n";
                f << "  \"path\": \"StarforgeApp::BuildScripts -> BuildRunner (cmake configure+build) -> StarforgeApp::ReloadModule -> GameModule\",\n";
                f << "  \"project\": \"" << Esc(t.projectDir) << "\",\n  \"cycles_planned\": " << t.cyclesPlanned << ",\n";
                f << "  \"cycles_run\": " << t.cycle + (t.phase == P::Finish && t.cycles.size() > (size_t)t.cycle ? 0 : 0) << ",\n";
                f << "  \"builds\": " << t.cycles.size() << ",\n  \"successful_rebuild_reloads\": " << t.successful << ",\n";
                f << "  \"reflected_field_changes\": " << t.reflectedChanges << ",\n";
                f << "  \"compile_failure_recovered\": " << (t.compileFailSeen ? "true" : "false") << ",\n";
                f << "  \"module_load_failure_recovered\": " << (t.loadFailSeen ? "true" : "false") << ",\n";
                f << "  \"failed_checks\": " << t.failures << ",\n  \"total_seconds\": " << total << ",\n";
                f << "  \"verdict\": \"" << (pass ? "PASS" : "FAIL") << "\",\n  \"checks_failed\": [\n";
                for (size_t i = 0; i < t.checks.size(); ++i) f << "    \"" << Esc(t.checks[i]) << "\"" << (i + 1 < t.checks.size() ? "," : "") << "\n";
                f << "  ],\n  \"cycles\": [\n";
                for (size_t i = 0; i < t.cycles.size(); ++i) f << "    " << t.cycles[i] << (i + 1 < t.cycles.size() ? "," : "") << "\n";
                f << "  ],\n  \"log\": [\n";
                for (size_t i = 0; i < t.log.size(); ++i) f << "    \"" << Esc(t.log[i]) << "\"" << (i + 1 < t.log.size() ? "," : "") << "\n";
                f << "  ]\n}\n";
                f.close();
            }
            // The editor console (every cmake line, every [Module]/[Build] message).
            {
                std::ofstream c(fs::path(t.resultPath).parent_path() / "l02-editor-console.txt", std::ios::trunc);
                for (const auto& l : m_Ctx.ConsoleLines) c << l.Text << "\n";
            }
            std::printf("L02_SELFTEST_RESULT=%s config=%s successful=%d/%d reflectedChanges=%d compileFail=%d loadFail=%d failedChecks=%d seconds=%.0f\n",
                        pass ? "PASS" : "FAIL", cfg, t.successful, t.cyclesPlanned, t.reflectedChanges,
                        t.compileFailSeen ? 1 : 0, t.loadFailSeen ? 1 : 0, t.failures, total);
            std::fflush(stdout);
            t.phase = P::Done;
            if (pass) Cosmic::Application::Get().Close();
            else      std::quick_exit(1);
            return;
        }

        case P::Done:
        default:
            return;
        }
    }
}
