// Module.cpp — @PROJECT_NAME@ game module (blank template, generated by Starforge).
//
// CS_MODULE_BEGIN/END expand to the two exports the engine expects:
//   * CosmicModule_Register(ModuleRegistry&) — scripts + custom components (the
//     editor calls this on hot reload);
//   * CreatePluginLayer() -> Cosmic::PlayerLayer — the standalone player, run by
//     the Launcher / `CosmicApp --project @PROJECT_NAME@` / a packaged exe.
//
// Add one CS_SCRIPT / CS_COMPONENT / CS_SERVICE block per class. Rebuild in the
// editor with "Build Scripts" (Ctrl+B). Screen scripts created by Starforge ▸
// Screens land between the CS_SCREENS markers — leave the markers in place.

#include <Cosmic.h>

CS_MODULE_BEGIN(@PROJECT_NAME@)
    // CS_SCREENS_BEGIN — managed by Starforge ▸ Screens (one CS_SCRIPT per screen script)
    // CS_SCREENS_END
CS_MODULE_END()
