#pragma once

// Window.h
// Last Modified 5/14/2026

/**
 * General Description:
 * The Window class acts as the primary interface between the Cosmic Engine and the
 * underlying Operating System. It abstracts the complexities of window creation,
 * hardware input management, and graphics context ownership. By utilizing GLFW,
 * it provides a platform-agnostic surface for rendering while translating native
 * OS messages (keyboard, mouse, window state) into the engine's internal Event system.
 *
 * Public Function Prototypes (Pre and Post Conditions):
 *
 * 1. Window(int width, int height, const std::string& title)
 *    Pre:  The platform's windowing API (GLFW) must be capable of initialization.
 *    Post: A native window and a specialized GraphicsContext (OpenGL) are created;
 *          internal WindowData is initialized and callbacks are bound to the OS.
 *
 * 2. ~Window()
 *    Pre:  A valid Window instance exists.
 *    Post: The GraphicsContext is deleted, the native window is destroyed, and
 *          windowing resources are released.
 *
 * 3. void PollEvents()
 *    Pre:  None.
 *    Post: Triggers the OS to process all pending input signals, which are then
 *          dispatched via the registered EventCallback.
 *
 * 4. void SwapBuffers()
 *    Pre:  The GraphicsContext has been successfully initialized.
 *    Post: Swaps the front and back buffers, presenting the rendered frame to the user.
 *
 * 5. unsigned int GetWidth() / GetHeight()
 *    Pre:  None.
 *    Post: Returns the current cached dimensions of the window.
 *
 * 6. GLFWwindow* GetHandle()
 *    Pre:  None.
 *    Post: Returns the raw pointer to the underlying GLFW window handle for
 *          API-specific operations.
 *
 * 7. void SetEventCallback(const EventCallbackFn& callback)
 *    Pre:  None.
 *    Post: Sets the target function that will receive all events generated by
 *          this window.
 *
 * 8. void SetVSync(bool enabled)
 *    Pre:  A valid GraphicsContext is active.
 *    Post: Synchronizes the physical buffer swap with the monitor's refresh rate.
 *
 * 9. bool IsVSync()
 *    Pre:  None.
 *    Post: Returns true if Vertical Sync is currently enabled.
 *
 * 10. bool ShouldClose()
 *     Pre:  None.
 *     Post: Returns true if the OS has signaled that the window should be terminated.
 *
 * 11. void GetSize(int* width, int* height)
 *     Pre:  Pointers must be valid.
 *     Post: Queries the windowing API directly for the current framebuffer size.
 */

#include "graphics/GraphicsContext.h"
#include "events/Event.h"
#include <string>
#include <functional>

struct GLFWwindow; // Forward declaration to minimize header pollution

namespace Cosmic
{
	class Window
	{
	public:
		using EventCallbackFn = std::function<void(Event&)>;


		////////////////////////////////
		// Construction & Lifecycle
		///////////////////////////////

		Window(int width, int height, const std::string& title);
		~Window();


		////////////////////////////////
		// Frame & Event Management
		///////////////////////////////

		void						PollEvents();
		void						SwapBuffers();


		////////////////////////////////
		// Window Attributes (Accessors)
		///////////////////////////////

		inline unsigned int			GetWidth() const		{ return m_Data.Width; }
		inline unsigned int			GetHeight() const		{ return m_Data.Height; }
		inline GLFWwindow*			GetHandle() const		{ return m_Handle; }


		////////////////////////////////
		// Configuration & Callbacks
		///////////////////////////////

		void		SetEventCallback(const EventCallbackFn& callback)		{ m_Data.EventCallback = callback; }
		void		SetVSync(bool enabled);
		bool		IsVSync() const											{ return m_Data.VSync; }


		////////////////////////////////
		// Window State
		///////////////////////////////

		bool		ShouldClose() const;
		void		GetSize(int* width, int* height) const;



	private:
		///////////////////////////////
		// Platform-Specific Handles
		///////////////////////////////

		GLFWwindow* m_Handle;
		GraphicsContext* m_Context; // Owned API-specific context (e.g. OpenGLContext)


		///////////////////////////////
		// Internal State Container
		///////////////////////////////

		struct WindowData
		{
			std::string			Title;
			unsigned int		Width				= 0;
			unsigned int		Height				= 0;
			bool				VSync				= false;
			EventCallbackFn		EventCallback;
		};

		WindowData				m_Data;
	};
}