// Module.cpp — @PROJECT_NAME@ game module (generated by Starforge / E12).
//
// CS_MODULE_BEGIN/END expand to the two exports the engine expects:
//   * CosmicModule_Register(ModuleRegistry&) — scripts + custom components (the
//     editor calls this on hot reload);
//   * CreatePluginLayer() -> Cosmic::PlayerLayer — the standalone player, run by
//     the Launcher / `CosmicApp --project @PROJECT_NAME@` / a packaged exe.
//
// Add one CS_SCRIPT / CS_COMPONENT block per class. Rebuild in the editor with
// "Build Scripts" (Ctrl+B). Screen scripts created by Starforge ▸ Screens land
// between the CS_SCREENS markers below — leave the markers in place.

#include <Cosmic.h>

#include "scripts/BouncingBall.h"
#include "scripts/PidController.h"
#include "scripts/PhysicsBall.h"
#include "scripts/PaddleController.h"
#include "scripts/PongBall.h"
#include "scripts/StoryUiBinding.h"

CS_MODULE_BEGIN(@PROJECT_NAME@)
    // Telemetry demos (E20) — push channels sampled per fixed step during Play.
    CS_SCRIPT(BouncingBall)
        CS_FIELD(Gravity)
        CS_FIELD(Restitution).Range(0.0f, 1.0f)
        CS_FIELD(StartHeight).Range(0.0f, 50.0f)
        CS_FIELD(FloorY).Range(-50.0f, 50.0f)
    CS_END;

    CS_SCRIPT(PidController)
        CS_FIELD(Target).Range(0.0f, 50.0f)
        CS_FIELD(Kp)
        CS_FIELD(Ki)
        CS_FIELD(Kd)
    CS_END;

    // Telemetry reporter for a dynamic-rigid-body ball (Phase 15 / J9).
    CS_SCRIPT(PhysicsBall)
    CS_END;

    // ForgePong (Phase 17 / U8) — 2D sprites + UI + flow working together.
    CS_SCRIPT(PaddleController)
        CS_FIELD(Speed).Range(0.0f, 30.0f)
        CS_FIELD(LimitY).Range(0.0f, 10.0f)
        CS_FIELD(UseArrows)
    CS_END;

    CS_SCRIPT(PongBall)
        CS_FIELD(Speed).Range(1.0f, 30.0f)
        CS_FIELD(SpeedUp).Range(1.0f, 1.5f)
        CS_FIELD(CourtHalfW).Range(1.0f, 32.0f)
        CS_FIELD(CourtHalfH).Range(1.0f, 32.0f)
        CS_FIELD(WinScore).Range(1.0f, 99.0f)
    CS_END;

    // Story Graph UI binding (Phase 25 / Q3) — attach next to a canvas, point
    // StoryPath at a .cstory, tag the UI entities it drives.
    CS_SCRIPT(StoryUiBinding)
        CS_FIELD(StoryPath)
        CS_FIELD(TextTag)
        CS_FIELD(SpeakerTag)
        CS_FIELD(PortraitTag)
        CS_FIELD(BackgroundTag)
        CS_FIELD(OptionTagPrefix)
    CS_END;

    // CS_SCREENS_BEGIN — managed by Starforge ▸ Screens (one CS_SCRIPT per screen script)
    // CS_SCREENS_END
CS_MODULE_END()
