// Module.cpp — @PROJECT_NAME@ game module (generated by Starforge / E12).
//
// CS_MODULE_BEGIN/END expand to the two exports the engine expects:
//   * CosmicModule_Register(ModuleRegistry&) — scripts + custom components (the
//     editor calls this on hot reload);
//   * CreatePluginLayer() -> Cosmic::PlayerLayer — the standalone player, run by
//     the Launcher / `CosmicApp --project @PROJECT_NAME@` / a packaged exe.
//
// Add one CS_SCRIPT / CS_COMPONENT block per class. Rebuild in the editor with
// "Build Scripts" (Ctrl+B).

#include <Cosmic.h>

#include "scripts/HoverController.h"

CS_MODULE_BEGIN(@PROJECT_NAME@)
    CS_SCRIPT(HoverController)
        CS_FIELD(TargetAltitude).Range(0.0f, 100.0f)
        CS_FIELD(Kp)
        CS_FIELD(Kd)
    CS_END;
CS_MODULE_END()
