// Module.cpp — @PROJECT_NAME@ game module (generated by Starforge / E12).
//
// CS_MODULE_BEGIN/END expand to the two exports the engine expects:
//   * CosmicModule_Register(ModuleRegistry&) — scripts + custom components (the
//     editor calls this on hot reload);
//   * CreatePluginLayer() -> Cosmic::PlayerLayer — the standalone player, run by
//     the Launcher / `CosmicApp --project @PROJECT_NAME@` / a packaged exe.
//
// Add one CS_SCRIPT / CS_COMPONENT block per class. Rebuild in the editor with
// "Build Scripts" (Ctrl+B).

#include <Cosmic.h>

#include "scripts/HoverController.h"
#include "scripts/BouncingBall.h"
#include "scripts/PidController.h"
#include "scripts/WalkController.h"
#include "scripts/PhysicsBall.h"
#include "scripts/VoxelDigger.h"
#include "scripts/PaddleController.h"
#include "scripts/PongBall.h"

CS_MODULE_BEGIN(@PROJECT_NAME@)
    CS_SCRIPT(HoverController)
        CS_FIELD(TargetAltitude).Range(0.0f, 100.0f)
        CS_FIELD(Kp)
        CS_FIELD(Kd)
    CS_END;

    // Telemetry demos (E20) — push channels sampled per fixed step during Play.
    CS_SCRIPT(BouncingBall)
        CS_FIELD(Gravity)
        CS_FIELD(Restitution).Range(0.0f, 1.0f)
        CS_FIELD(StartHeight).Range(0.0f, 50.0f)
        CS_FIELD(FloorY).Range(-50.0f, 50.0f)
    CS_END;

    CS_SCRIPT(PidController)
        CS_FIELD(Target).Range(0.0f, 50.0f)
        CS_FIELD(Kp)
        CS_FIELD(Ki)
        CS_FIELD(Kd)
    CS_END;

    // Physics character walker (Phase 15 / J6) — attach with a
    // CharacterControllerComponent; WASD / left stick walk, Space jumps.
    CS_SCRIPT(WalkController)
        CS_FIELD(MoveSpeed).Range(0.0f, 20.0f)
        CS_FIELD(JumpSpeed).Range(0.0f, 20.0f)
    CS_END;

    // Telemetry reporter for a dynamic-rigid-body ball (Phase 15 / J9).
    CS_SCRIPT(PhysicsBall)
    CS_END;

    // Voxel place/break (Phase 18 / V4) — LMB digs, RMB places along forward.
    CS_SCRIPT(VoxelDigger)
        CS_FIELD(Reach).Range(1.0f, 32.0f)
        CS_FIELD(PlaceBlock).Range(0.0f, 16.0f)
        CS_FIELD(EyeHeight).Range(0.0f, 4.0f)
    CS_END;

    // ForgePong (Phase 17 / U8) — 2D sprites + UI + flow working together.
    CS_SCRIPT(PaddleController)
        CS_FIELD(Speed).Range(0.0f, 30.0f)
        CS_FIELD(LimitY).Range(0.0f, 10.0f)
        CS_FIELD(UseArrows)
    CS_END;

    CS_SCRIPT(PongBall)
        CS_FIELD(Speed).Range(1.0f, 30.0f)
        CS_FIELD(SpeedUp).Range(1.0f, 1.5f)
        CS_FIELD(CourtHalfW).Range(1.0f, 32.0f)
        CS_FIELD(CourtHalfH).Range(1.0f, 32.0f)
        CS_FIELD(WinScore).Range(1.0f, 99.0f)
    CS_END;
CS_MODULE_END()
