#pragma once
// layers/PlayerLayer.h
//
// ============================================================================
// Cosmic standalone scene player (Phase 13 / E13 / §3.4).
// ============================================================================
//
// The engine-generic layer that runs a Starforge-made project with NO editor
// anywhere. A scaffolded project's CreatePluginLayer (generated by CS_MODULE_END)
// registers the module on its own handle and returns one of these; the Launcher /
// `--project <Name>` / a packaged exe then run it. It:
//
//   * sets the VFS active project + reads project://project.cproj (startup scene,
//     fixed-dt Hz, window title) — utils/Config TOML;
//   * loads the startup scene through the SceneManager (E5);
//   * instantiates + ticks the scene's NativeScript components (ScriptHost, E11),
//     variable ticks in OnUpdate and fixed ticks in OnFixedUpdate — so first-class
//     pause (Application::Pause, Feature B) freezes the sim while the frame keeps
//     drawing;
//   * renders the scene from its first Primary CameraComponent (E4), falling back
//     to a default view + a one-time warning;
//   * offers a minimal Esc pause menu (Resume / Quit to Launcher).
//
// This is what makes "ship from the editor" free — the SAME project DLL that the
// editor hot-reloads is the one the player runs. Rendering goes through the engine
// SceneRenderer (H2) — the SAME env/sky/shadow/HDR/post path the editor viewport
// uses — so a packaged app looks byte-identical to the editor.
// ============================================================================

#include "core/Core.h"
#include "core/Layer.h"
#include "scene/SceneManager.h"
#include "scene/FlowMachine.h"        // U5 — optional startup screen-flow
#include "scripting/ScriptHost.h"
#include "renderer/SceneRenderer.h"   // H2 — the shared render path
#include "physics/PhysicsWorld.h"     // J4 — the play-session physics service

#include <string>

namespace Cosmic
{
    class Scene;
    class Event;
    class PlayerCamera;   // concrete Camera, defined in PlayerLayer.cpp

    class COSMIC_API PlayerLayer : public Layer
    {
    public:
        // projectName == the VFS project folder (assets/projects/<name>) the DLL
        // ships in. Empty leaves the active project as-is (already set by the host).
        explicit PlayerLayer(const std::string& projectName = "");
        ~PlayerLayer() override;

        void OnAttach() override;
        void OnDetach() override;
        void OnUpdate(float ts) override;
        void OnFixedUpdate(float fixedDt) override;
        void OnImGuiRender() override;
        void OnEvent(Event& e) override;

    private:
        void RebindScripts();          // (re)instantiate scripts when the scene swaps
        void UpdateCamera(float aspect);
        void RenderScene(float dt);
        void UpdateUI(float dt);       // U1 — pointer interaction -> scene EventBus
        Ref<Scene> LoadSceneFile(const std::string& path);  // U5 flow loader

        std::string  m_ProjectName;
        std::string  m_StartupScene = "scenes/Main.cscene";
        SceneManager m_Scenes{ 0.0f };  // no fade in v1 (overlay draw is a follow-up)
        ScriptHost   m_Scripts;
        Ref<Scene>   m_TrackedScene;    // last scene we instantiated scripts for
        Scope<PlayerCamera> m_Camera;
        SceneRenderer m_SceneRenderer;  // H2 — env/sky/shadow/HDR/post (== editor)
        PhysicsWorld  m_Physics;        // J4 — owned here; scenes bind/unbind to it
        bool m_MissingCameraWarned = false;

        // U5 — optional screen-flow. Active only when project.cproj names a
        // "startup_flow"; otherwise the single-startup-scene path is unchanged.
        FlowMachine m_Flow;
        bool        m_UseFlow = false;
        // U1 — pointer edge tracking for UI interaction / key-signal feed.
        bool m_PrevMouseDown = false;
        bool m_PrevEscape    = false;
        // U7 — mouse-look capture ("capture_cursor" manifest key): captured on
        // boot, Esc releases, a click inside the window recaptures.
        bool m_CaptureCursor = false;
    };
}
