#pragma once
// layers/PlayerLayer.h
//
// ============================================================================
// Cosmic standalone scene player (Phase 13 / E13 / §3.4).
// ============================================================================
//
// The engine-generic layer that runs a Starforge-made project with NO editor
// anywhere. A scaffolded project's CreatePluginLayer (generated by CS_MODULE_END)
// registers the module on its own handle and returns one of these; the Launcher /
// `--project <Name>` / a packaged exe then run it. It:
//
//   * sets the VFS active project + reads project://project.cproj (startup scene,
//     fixed-dt Hz, window title) — utils/Config TOML;
//   * loads the startup scene through the SceneManager (E5);
//   * instantiates + ticks the scene's NativeScript components (ScriptHost, E11),
//     variable ticks in OnUpdate and fixed ticks in OnFixedUpdate — so first-class
//     pause (Application::Pause, Feature B) freezes the sim while the frame keeps
//     drawing;
//   * renders the scene from its first Primary CameraComponent (E4), falling back
//     to a default view + a one-time warning;
//   * offers a minimal Esc pause menu (Resume / Quit to Launcher).
//
// This is what makes "ship from the editor" free — the SAME project DLL that the
// editor hot-reloads is the one the player runs. Rendering uses Scene::OnRender3D
// (the editor viewport's path); the SceneRenderer env/shadow/post upgrade is a
// shared follow-up for both surfaces.
// ============================================================================

#include "core/Core.h"
#include "core/Layer.h"
#include "scene/SceneManager.h"
#include "scripting/ScriptHost.h"

#include <string>

namespace Cosmic
{
    class Scene;
    class Event;
    class PlayerCamera;   // concrete Camera, defined in PlayerLayer.cpp

    class COSMIC_API PlayerLayer : public Layer
    {
    public:
        // projectName == the VFS project folder (assets/projects/<name>) the DLL
        // ships in. Empty leaves the active project as-is (already set by the host).
        explicit PlayerLayer(const std::string& projectName = "");
        ~PlayerLayer() override;

        void OnAttach() override;
        void OnDetach() override;
        void OnUpdate(float ts) override;
        void OnFixedUpdate(float fixedDt) override;
        void OnImGuiRender() override;
        void OnEvent(Event& e) override;

    private:
        void RebindScripts();          // (re)instantiate scripts when the scene swaps
        void UpdateCamera(float aspect);
        void RenderScene(float dt);

        std::string  m_ProjectName;
        std::string  m_StartupScene = "scenes/Main.cscene";
        SceneManager m_Scenes{ 0.0f };  // no fade in v1 (overlay draw is a follow-up)
        ScriptHost   m_Scripts;
        Ref<Scene>   m_TrackedScene;    // last scene we instantiated scripts for
        Scope<PlayerCamera> m_Camera;
        bool m_MissingCameraWarned = false;
    };
}
